import Link from "next/link"
import { loadForgeEconomics, type EconomicsFilters } from "@/lib/server/forge-economics"

export const dynamic="force-dynamic"; export const runtime="nodejs"
export default async function ForgeEconomicsPage({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){const query=await searchParams;const filters=parse(query);const data=await loadForgeEconomics(filters);const s=data.summary;return <div className="mx-auto max-w-7xl space-y-5 p-4"><div className="flex flex-wrap items-end justify-between gap-3"><div><Link href="/forge" className="text-sm text-cyan-300">← Forge</Link><h1 className="font-syne text-3xl font-bold">Forge economics</h1><p className="text-sm text-t2">AI costs are internal estimates from normalized token usage. Revenue and margin are estimates from proposal values—not confirmed provider invoices or collected billing.</p></div><a className="rounded bg-cyan-300 px-3 py-2 text-sm font-bold text-slate-950" href={`/api/forge/economics/export?${new URLSearchParams(stringFilters(filters))}`}>Export CSV</a></div><Filters filters={filters} options={data.options}/>{data.alerts.length>0&&<div className="rounded border border-amber-500/30 bg-amber-500/10 p-4 text-sm text-amber-200"><strong>Economics alerts</strong><ul className="mt-2 list-disc pl-5">{data.alerts.map(a=><li key={a}>{a}</li>)}</ul></div>}<div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Estimated AI cost" value={money(s.totalCost)}/><Metric label="Token usage" value={s.totalTokens.toLocaleString()}/><Metric label="Estimated retry cost" value={money(s.retryCost)}/><Metric label="Fallback rate" value={`${(s.fallbackRate*100).toFixed(1)}%`}/><Metric label="Average latency" value={s.averageLatencyMs===null?"No data":`${s.averageLatencyMs} ms`}/><Metric label="Cost / completed site" value={maybeMoney(s.costPerCompletedWebsite)}/><Metric label="Cost / approved artifact" value={maybeMoney(s.costPerApprovedArtifact)}/><Metric label="Cost / proposal" value={maybeMoney(s.costPerProposal)}/><Metric label="Estimated proposal value" value={money(s.estimatedRevenue)}/><Metric label="Estimated gross margin impact" value={money(s.estimatedGrossMarginImpact)}/></div><div className="grid gap-4 lg:grid-cols-2"><Breakdown title="Cost by project" rows={s.byProject}/><Breakdown title="Cost by client" rows={s.byClient}/><Breakdown title="Cost by agent/stage" rows={s.byStage}/><Breakdown title="Cost by provider" rows={s.byProvider}/><Breakdown title="Cost by model" rows={s.byModel}/><Breakdown title="Cost by day" rows={s.byDay}/></div><p className="text-xs text-t3">Weekly and monthly views are selected with the date filters. All monetary AI values shown are estimates; no confirmed provider billing feed is connected.</p></div>}
function Filters({filters,options}:{filters:EconomicsFilters;options:Awaited<ReturnType<typeof loadForgeEconomics>>["options"]}){return <form className="grid gap-2 rounded border border-b1 bg-s1 p-3 sm:grid-cols-2 lg:grid-cols-7"><input type="date" name="from" defaultValue={filters.from}/><input type="date" name="to" defaultValue={filters.to}/><Select name="projectId" value={filters.projectId} items={options.projects.map(x=>[x.id,x.name])}/><Select name="clientId" value={filters.clientId} items={options.clients.map(x=>[x.id,x.name])}/><Select name="provider" value={filters.provider} items={options.providers.map(x=>[x,x])}/><Select name="stage" value={filters.stage} items={options.stages.map(x=>[x!,x!])}/><button className="rounded bg-cyan-300 px-3 text-slate-950">Apply filters</button></form>}
function Select({name,value,items}:{name:string;value:string|number|undefined;items:Array<[string|number,string]>}){return <select name={name} defaultValue={value??""}><option value="">All {name.replace("Id","")}</option>{items.map(([id,label])=><option key={id} value={id}>{label}</option>)}</select>}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded border border-b1 bg-s1 p-4"><p className="text-xs uppercase tracking-wide text-t3">{label}</p><p className="mt-2 text-2xl font-bold">{value}</p></div>}
function Breakdown({title,rows}:{title:string;rows:Array<{label:string;cost:number}>}){return <section className="rounded border border-b1 bg-s1 p-4"><h2 className="font-semibold">{title}</h2><div className="mt-3 max-h-64 overflow-auto">{rows.length?rows.map(r=><div key={r.label} className="flex justify-between border-b border-b1 py-2 text-sm"><span>{r.label}</span><span>{money(r.cost)} estimated</span></div>):<p className="text-sm text-t3">No usage in this filter.</p>}</div></section>}
function parse(q:Record<string,string|string[]|undefined>):EconomicsFilters{const one=(k:string)=>typeof q[k]==="string"?q[k] as string:undefined;const num=(k:string)=>{const n=Number(one(k));return Number.isInteger(n)&&n>0?n:undefined};return{from:one("from"),to:one("to"),projectId:num("projectId"),clientId:num("clientId"),provider:one("provider"),model:one("model"),stage:one("stage")}}
function stringFilters(f:EconomicsFilters){return Object.fromEntries(Object.entries(f).filter(([,v])=>v!==undefined).map(([k,v])=>[k,String(v)]))}function money(n:number){return new Intl.NumberFormat("en-GB",{style:"currency",currency:"GBP",maximumFractionDigits:4}).format(n)}function maybeMoney(n:number|null){return n===null?"No denominator":money(n)}
