import { managedBusinessEmail, managedBusinessEmailPriceLabel } from "./managed-business-email"
import { legalEntity, type LegalSlug } from "./legal"
import { storageInventory } from "./cookie-consent"
import { businessGrowthAudit, formatAuditPrice } from "./business-growth-audit"

export type PolicySection = { title: string; paragraphs?: string[]; bullets?: string[] }
export type LegalPolicy = { title: string; introduction: string; sections: PolicySection[] }
const contact = legalEntity.contactEmail
const commonChanges: PolicySection = { title: "Changes and contact", paragraphs: [`We may update this document when services, operating practices or law change. The published version and date identify the current terms. Where a material change affects an active paid service, ScaleSmiths will give reasonable notice where appropriate and will not retrospectively remove accrued rights. Questions may be sent to ${contact}.`] }

export const legalPolicies: Record<LegalSlug, LegalPolicy> = {
  privacy: {
    title: "Privacy Notice", introduction: "How ScaleSmiths handles personal information as a controller and, for some client services, as a processor.", sections: [
      { title: "Who ScaleSmiths is", paragraphs: [`ScaleSmiths is the trading name used by a digital services business operating from ${legalEntity.businessLocation}. The repository does not establish a registered-company identity, company number, registered office or VAT status, so this notice does not claim them. Contact ${contact} for privacy matters.`, "ScaleSmiths is an independent controller for enquiries, prospects, client administration, billing records, its own marketing and security records. Where ScaleSmiths hosts or operates a client system, processes the client's end-customer information on documented instructions, or provides managed email in a processor capacity, the client is normally controller and the Data Processing Addendum applies." ] },
      { title: "Information handled", bullets: ["Identity, contact and business details; project enquiries, quotes, communications and requested services.", "Portal account identifiers, password hashes, project files, requests, messages, decisions, reports and access/security records.", "Billing and transaction metadata supplied through agreed commercial processes; the public site does not collect card details.", "IP addresses, request identifiers, device/browser information, restricted logs, rate-limit hashes and security events.", "Domain names, DNS provider details, authorised DNS instructions, mailbox identifiers, account-administration information and communications metadata.", "For managed email, message content and attachments may be stored and transmitted as part of providing the service. ScaleSmiths does not routinely read mailbox content; access is limited to authorised support requested by the client, security or abuse investigation, legal obligation, or protecting and maintaining the service."] },
      { title: "Purposes and lawful bases", bullets: ["Responding to enquiries and preparing proposals: steps requested before contract and legitimate interests in handling genuine business enquiries.", "Delivering services, support, portal access and account administration: contract and legitimate interests in documenting delivery.", "Billing, tax and accounting records: contract and legal obligation.", "Security, fraud and abuse prevention, service logs and incident handling: legitimate interests and legal obligations where applicable.", "Service improvement and first-party analytics: consent for optional browser storage and legitimate interests in aggregated analysis.", "Direct marketing: consent or legitimate interests only where legally appropriate, always subject to PECR.", "Compliance, disputes and legal claims: legal obligation and legitimate interests in establishing, exercising or defending claims."] },
      { title: "Direct marketing", paragraphs: ["An enquiry permission is not marketing consent. ScaleSmiths does not treat a publicly listed address as permission to market to an individual or sole trader. Corporate subscribers and individual subscribers can be treated differently under PECR, but UK GDPR still applies where personal data is used. Any consent must be specific, informed, freely given and affirmative; marketing messages must identify ScaleSmiths and provide an appropriate opt-out. Objections are honoured and a minimal suppression record may be retained to prevent accidental re-contact."] },
      { title: "Recipients and international transfers", paragraphs: ["Information is limited to authorised ScaleSmiths personnel, the production VPS hosting provider (who hosts application containers, the PostgreSQL database and generated workspaces), Resend for transactional email delivery, and professional advisers and authorities where disclosure is lawful. Sentry, Cloudflare, and AI providers (OpenAI/Anthropic) are documented as configurable but are not active in the current production configuration. Where a restricted transfer occurs, ScaleSmiths must use a UK adequacy regulation, the UK IDTA/Addendum with an appropriate transfer assessment, or another lawful mechanism. The Subprocessor List identifies the current status of each provider."] },
      { title: "Retention", bullets: ["Enquiries: reviewed periodically and deleted or reduced when no longer commercially active, subject to dispute or legal-record needs.", "Contracts, invoices and accounting evidence: retained for the applicable statutory, tax and claims periods set by the operational retention schedule.", "Portal, support and project records: active relationship plus the proportionate period documented for delivery, disputes and legal obligations.", "Security and rate-limit records: limited to operational, incident and defence needs; rate-limit enforcement uses ten-minute windows.", "Analytics events: used for short-window aggregate reporting and then aggregated or removed under the operational schedule.", "Marketing suppression records: retained as long as reasonably necessary to honour the objection.", "Mailbox administration and email data: for the contracted service, then returned or deleted under the DPA and offboarding plan; residual backup copies expire through backup rotation rather than being promised immediate deletion."] },
      { title: "Your rights and complaints", paragraphs: ["Depending on the circumstances, rights may include access, correction, erasure, restriction, objection, portability and withdrawal of consent. They are not absolute and exemptions or competing obligations may apply. You have an unconditional right to object to direct marketing. Contact ScaleSmiths first at the address above; you may also complain to the Information Commissioner's Office at ico.org.uk."] },
      commonChanges,
    ],
  },
  cookies: { title: "Cookie Policy", introduction: "The actual cookies and browser storage used by the ScaleSmiths public website and client portal.", sections: [
    { title: "How choices work", paragraphs: ["Cookies and similar storage allow a site to remember information in a browser. Strictly necessary storage operates for a requested service or to remember a privacy choice. Functional and analytics storage remain off until the visitor gives category consent. Rejecting non-essential storage does not block public content. Cookie Settings in the footer allows withdrawal at any time; withdrawal applies going forward."] },
    { title: "Current inventory", bullets: storageInventory.map((item) => `${item.name} — ${item.provider}; ${item.purpose} Category: ${item.category}. Duration: ${item.duration}. ${item.party}. ${item.consent}.`) },
    { title: "Third-party technologies", paragraphs: ["The public application does not currently deploy advertising pixels, behavioural marketing tags, embedded video trackers or a card-payment widget. Resend is used server-side for transactional email delivery. Sentry is server-side error monitoring, currently disabled. OpenAI and Anthropic are Forge AI providers, currently disabled. Cloudflare network/proxy services are documented as optional and are not currently active in production. No Cloudflare browser analytics script, Cloudflare Insights beacon, or other third-party tracking script is deliberately loaded by application code. These services are not activated through the marketing category in this preference tool."] },
    { title: "Exceptions relied upon", paragraphs: ["ScaleSmiths relies only on the strictly necessary exception for the portal session and recording the visitor's privacy choice. Although current UK law provides limited statistical and appearance/functionality exceptions, ScaleSmiths does not rely on them for first-party experience analytics or saved experience preferences: uncertainty is resolved by requiring consent."] },
    commonChanges,
  ] },
  "website-terms": { title: "Website Terms", introduction: "Terms for lawful use of scalesmiths.co.uk and its public information.", sections: [
    { title: "Operator and permitted use", paragraphs: [`ScaleSmiths operates from ${legalEntity.businessLocation}; contact ${contact}. You may browse and make reasonable internal copies to evaluate services. You must not use the site for unlawful activity, malware, credential theft, unauthorised access, destructive security testing, form spam, impersonation, or scraping that materially impairs the service.`] },
    { title: "Information, availability and links", paragraphs: ["Public content is general information, not legal, financial or professional advice for a particular situation. It may change or contain errors. The site may be unavailable for maintenance, security or circumstances outside reasonable control. Third-party sites and services remain under their operators' control."] },
    { title: "Intellectual property", paragraphs: ["ScaleSmiths owns or licenses its website design, software, branding, text and graphics. Client names and public project materials remain subject to their owners' rights and permissions. Project deliverable ownership is governed by the signed project documents, not these browsing terms."] },
    { title: "Liability and law", paragraphs: ["Nothing excludes liability for death or personal injury caused by negligence, fraud, fraudulent misrepresentation or anything else that cannot lawfully be excluded. Subject to that protection, responsibility for paid services is governed by the applicable client agreement. These terms are governed by England and Wales law and its courts, subject to mandatory rights that apply."] }, commonChanges,
  ] },
  "service-terms": { title: "Master Service Terms", introduction: "The default B2B terms for ScaleSmiths projects and managed services, unless signed documents state otherwise.", sections: [
    { title: "Contract documents and scope", paragraphs: ["The order of precedence is: signed statement of work, order form or proposal; Data Processing Addendum; service-specific terms; these Master Service Terms; Website Terms. A negotiated signed term prevails only on the point it addresses. Submitting an enquiry is not an order. Scope, price, VAT treatment, billing schedule, delivery assumptions and acceptance process must appear in agreed project documents."] },
    { title: "Business Growth Audit", paragraphs: [`The Business Growth Audit is a one-time professional consulting product priced at ${formatAuditPrice()}. It provides standalone findings and a prioritised roadmap; it does not require the client to commission implementation. If the client later commissions an eligible ScaleSmiths build, the full ${formatAuditPrice(businessGrowthAudit.buildCreditMinor)} Audit fee is credited against that build. The applicable project proposal confirms eligibility before the build is commissioned; no expiry date or minimum project value is created by these online terms. The delivery date is confirmed before Audit work begins.`] },
    { title: "Client responsibilities and changes", paragraphs: ["The client must provide lawful materials, accurate information, timely decisions, approvals and appropriately secure access. Delays in client dependencies may move delivery dates. Out-of-scope work, changed assumptions or additional integrations require an agreed change, fee and timetable before work proceeds."] },
    { title: "Delivery, acceptance and payment", paragraphs: ["ScaleSmiths provides services with reasonable care and skill. The agreed review process gives the client a reasonable opportunity to identify material non-conformity; silence does not permanently waive hidden defects. Payment terms are those in the signed order. ScaleSmiths may proportionately pause work for material non-payment or prolonged missing dependencies after reasonable notice where circumstances allow."] },
    { title: "Intellectual property and portfolio", paragraphs: ["Clients retain their materials, trademarks and business data. ScaleSmiths retains pre-existing tools, frameworks, methods and know-how. Third-party and open-source components remain under their licences. Bespoke deliverable ownership or licence follows the signed project documents and any transfer occurs only after applicable agreed fees are paid. ScaleSmiths may identify and display completed public-facing work unless confidentiality, safety or a written agreement prevents this; confidential portals, databases and non-public information are excluded."] },
    { title: "Confidentiality and client data", paragraphs: ["Each party protects non-public business, technical and credential information and uses it only for the relationship. Exceptions include information already public without breach, independently developed or lawfully received, or required by law. Clients remain owners/controllers of their business data where applicable; ScaleSmiths receives only rights needed to host, process, transmit, back up, support and secure it."] },
    { title: "Third parties, outcomes and liability", paragraphs: ["External platforms, APIs, registrars, search engines and client-selected tools may change or fail outside ScaleSmiths' control, but this does not excuse ScaleSmiths' own failure to use reasonable care. No ranking, indexing, revenue, uninterrupted service, permanent compatibility or error-free result is guaranteed. No financial liability cap is stated here because it requires an express owner commercial decision and qualified legal review. Nothing excludes non-excludable liability."] },
    { title: "Ending services", paragraphs: ["Termination, notice, outstanding fees, handover and transition follow the signed order and applicable service terms. Access may end; reasonable export or migration work may be scoped separately. Lawfully retained records and backup copies may remain for their scheduled rotation or legal purpose. Nothing affects rights that cannot lawfully be excluded."] }, commonChanges,
  ] },
  "hosting-terms": { title: "Hosting & Infrastructure Terms", introduction: "Service-specific terms for systems ScaleSmiths agrees to host, deploy, maintain or monitor.", sections: [
    { title: "Agreed service", paragraphs: ["The order defines the applications, environments, monitoring, maintenance, backups, support and exclusions. No uptime percentage, RPO, RTO, geographic redundancy or guaranteed restoration is created by these online terms."] },
    { title: "Operation and maintenance", paragraphs: ["ScaleSmiths may perform scheduled or emergency maintenance, security updates and proportionate protective action. Clients must maintain authorised contacts, lawful content, current dependencies within their control and independent copies of irreplaceable source and business material. Backups reduce risk but do not make loss impossible or replace the client's own continuity responsibilities."] },
    { title: "External dependencies and incidents", paragraphs: ["Hosting, networks, DNS, registrars and external APIs may fail or change. ScaleSmiths will use reasonable care within its agreed scope and communicate material incidents appropriately, without guaranteeing third-party availability. Security, abuse or material non-payment may justify proportionate restriction or suspension, with notice where reasonable and safe."] },
    { title: "Exit", paragraphs: ["On termination, hosted access may end. Export, migration and continued hosting must be agreed before the end date. Residual backups expire through scheduled rotation and records required by law may remain restricted."] }, commonChanges,
  ] },
  "email-terms": { title: "Managed Business Email Terms", introduction: "Service-specific B2B terms for standalone and retained ScaleSmiths Managed Business Email.", sections: [
    { title: "Starting service", paragraphs: [`The confirmed standalone starting offer is ${managedBusinessEmailPriceLabel()} for ${managedBusinessEmail.standalone.mailboxes} custom-domain mailboxes with ${managedBusinessEmail.standalone.storagePerMailboxGb}GB storage per mailbox and initial setup included. It includes webmail, compatible standard desktop/mobile access, spam filtering, TLS-supported transport, aliases/forwarding where configured, SPF, DKIM and DMARC configuration, and managed administration/support. Billing interval, VAT treatment and recurring-payment terms must be confirmed in the order; these terms do not invent them.`] },
    { title: "Business use and authority", paragraphs: ["The service is intended wholly or mainly for legitimate business, trade, craft or professional purposes. The person ordering confirms authority to act for the business. This does not reclassify a genuine consumer or remove mandatory consumer rights."] },
    { title: "Permitted purpose and customer duties", paragraphs: ["This is ordinary business communications infrastructure, not bulk marketing, cold-email blasting, spam, phishing, newsletter distribution at mass scale or high-volume machine-generated sending unless separately agreed. Customers must protect credentials, use authorised users, report compromise, comply with UK GDPR and PECR, respect objections and suppression records, and not send malware, fraud, unlawful impersonation, harassment or infringing content. A public address is not unrestricted marketing permission."] },
    { title: "Security, filtering and delivery", paragraphs: ["ScaleSmiths uses appropriate measures within the agreed service, but does not promise perfect spam or malware detection, end-to-end encryption, zero loss or guaranteed delivery. Receiving systems independently decide acceptance, filtering, reputation and inbox placement. SPF, DKIM and DMARC support authentication but do not guarantee delivery."] },
    { title: "Storage and fair use", paragraphs: [`Mailbox data counts towards the ${managedBusinessEmail.standalone.storagePerMailboxGb}GB limit. A full mailbox may stop accepting or storing additional mail until data is deleted, archived or a suitable alternative is agreed. No automatic overage price or larger public tier is created. Support covers setup, mailbox configuration, account/password issues and service faults—not unrelated device repair, a general IT helpdesk or unlimited migration consultancy.`] },
    { title: "Abuse and termination", paragraphs: ["ScaleSmiths may investigate credible reports, rate-limit suspicious sending, block malicious traffic, reset compromised credentials and proportionately suspend affected accounts. Immediate action may be needed to stop fraud, compromise or reputation damage; notice will be given where reasonable and safe. Before termination the client must export or migrate required mail. Domain ownership remains with the registrant; transition assistance may be separately scoped."] }, commonChanges,
  ] },
  "domain-dns-terms": { title: "Domain & DNS Management Terms", introduction: "Authority and safeguards for DNS changes made for agreed ScaleSmiths services.", sections: [
    { title: "Authority", paragraphs: ["The client confirms it owns or controls the domain or is authorised to instruct ScaleSmiths. It authorises only changes reasonably necessary for the agreed work, which may include A, AAAA, CNAME, MX, TXT, SPF, DKIM, DMARC and verification records."] },
    { title: "Ownership and access", paragraphs: ["The client remains registrant unless a separate transfer is expressly agreed. ScaleSmiths does not request registrar passwords through ordinary public forms. Delegated or scoped access should be used where supported, with secure exchange arranged during onboarding."] },
    { title: "Change risk", paragraphs: ["DNS changes can affect websites, email, verification and connected services. ScaleSmiths will use reasonable care, record scope where appropriate and may require confirmation of unknown dependencies. Neither party should make conflicting changes during a planned migration without coordination."] }, commonChanges,
  ] },
  "acceptable-use": { title: "Acceptable Use Policy", introduction: "Rules protecting customers, users and managed infrastructure from unlawful or harmful use.", sections: [
    { title: "Prohibited activity", bullets: ["Unlawful activity, fraud, phishing, impersonation, credential theft or illegal personal-data processing.", "Malware, botnets, denial-of-service activity, unauthorised scanning, exploitation or security circumvention.", "Spam, abusive unsolicited messaging, deliberate reputation damage or evasion of provider safeguards.", "Illegal content, unlawful harassment or threats, and knowing intellectual-property infringement.", "Using portal, hosting, applications or email to compromise another person, service or network."] },
    { title: "Response", paragraphs: ["ScaleSmiths may investigate credible reports, preserve relevant evidence, restrict harmful traffic and proportionately suspend the affected service. Serious, repeated or unlawful breaches may result in termination under the contract. Notice is provided where reasonable and safe; urgent action may precede notice to contain harm or meet legal duties."] }, commonChanges,
  ] },
  "fair-use": { title: "Fair Use Policy", introduction: "How ScaleSmiths protects shared resources while supporting ordinary legitimate business use.", sections: [
    { title: "Reasonable use", paragraphs: [`Pricing assumes ordinary business use of storage, sending, connections, bandwidth, compute, automated processes, backups and support. The only public numerical resource limit is ${managedBusinessEmail.standalone.storagePerMailboxGb}GB per mailbox in the starting email service; this policy does not create hidden numerical caps.`] },
    { title: "Proportionate response", paragraphs: ["Where sustained usage materially affects security, stability or other customers, ScaleSmiths will normally discuss the pattern, help optimise it, and recommend a suitable service. Technical rate-limiting, migration, upgrade or suspension is used only where proportionate or immediately necessary. Fair use is not permission to throttle arbitrarily."] }, commonChanges,
  ] },
  "data-processing": { title: "Data Processing Addendum", introduction: "The Article 28 processor terms applying when a client controls personal data processed by ScaleSmiths on its behalf.", sections: [
    { title: "Roles and processing details", paragraphs: ["The client is controller where it determines purposes and means; ScaleSmiths is processor only for processing on documented instructions. Subject matter is the contracted website, application, portal, hosting, support or managed-email service; duration is the service term plus agreed return/deletion and backup rotation. Processing may include collection, receipt, storage, organisation, retrieval, transmission, filtering, backup, support, security monitoring and deletion.", "Data may include identities, contact details, account identifiers, client-customer records, messages, attachments, IP/security data and communications metadata. Data subjects may include client personnel, customers, suppliers, users and email correspondents. The order should narrow these details for the actual service."] },
    { title: "Processor obligations", bullets: ["Process only documented lawful instructions and notify the controller if an instruction appears unlawful, unless prohibited from doing so.", "Ensure authorised personnel are bound by confidentiality and apply appropriate technical and organisational measures.", "Use subprocessors under equivalent data-protection obligations and provide the current list/change process.", "Assist reasonably with rights requests, security, breach response, DPIAs and regulator consultation, taking account of the processing and information available.", "Notify the controller without undue delay after becoming aware of a personal-data breach affecting controller data.", "At the end, return or delete controller data as agreed, except lawful retention and backup rotation.", "Provide information reasonably necessary to demonstrate compliance and permit proportionate audits without compromising other customers or security.", "Maintain required processing records and use lawful safeguards for restricted transfers."] },
    { title: "Managed email", paragraphs: ["Email processing can include message content, attachments, addresses, traffic metadata, account identifiers and IP/security information relating to employees, customers, suppliers and correspondents. ScaleSmiths does not gain ownership of that content and limits administrative access to authorised support, maintenance, security, abuse or legal needs."] },
    { title: "Conflict", paragraphs: ["This Addendum prevails over general service terms on processor obligations. A signed processing schedule may replace or supplement it for the particular service."] }, commonChanges,
  ] },
  subprocessors: { title: "Subprocessor List", introduction: "Providers evidenced by the current application, plus gaps that must be closed before this list is treated as exhaustive.", sections: [
    { title: "Active application providers", bullets: ["Resend — transaction and service email delivery. Customer name, email, business and message content pass through Resend to deliver enquiry confirmations, client request notifications, and invoice emails with PDF attachments. The from-address uses a ScaleSmiths-owned domain. The Resend API region, DPA status and data-location settings are confirmed inside the Resend dashboard, not the repository; verify and record them.", "ScaleSmiths production PostgreSQL — application records stored on the production VPS. This is the self-hosted application database, not a distinct third-party processor. The responsible subprocessor is the VPS hosting provider (below)."] },
    { title: "Currently inactive or disabled (configure but verify before enabling)", bullets: ["Sentry — error monitoring via the server-side Sentry SDK. Currently inactive: ERROR_MONITORING_PROVIDER is set to none and no DSN is supplied. When enabled, only redacted exception metadata, correlation IDs, release identifiers and safe operational fields are transmitted, never form bodies, prompts, generated source, credentials, or personal-data rows. Confirm the Sentry organisation region, data retention and DPA before activation.", "OpenAI / Anthropic — Forge AI site-generation providers. Currently disabled: FORGE_ENABLE_AI is false and no API keys are supplied. When enabled, project requirements, copy content, and system prompts are transmitted to the selected provider's API. Budget controls cap spending. Confirm provider region, DPA, and zero-data-retention (ZDR) settings before activation.", "Cloudflare — network proxy, DNS, access control and security services. Not currently configured in production — the nginx host configuration documents Cloudflare as optional and no Cloudflare origin certificates or access policies are active. The CSP contains pre-emptive Cloudflare entries but no Cloudflare browser scripts are loaded. If Cloudflare is activated, request data, IP addresses and security events will be processed; confirm plan, region and log-retention settings."] },
    { title: "Owner input required", bullets: ["Production VPS hosting provider: legal entity name, datacentre location/region, and whether a DPA or equivalent contract is in place. This provider hosts the application containers, PostgreSQL database and generated workspaces.", "Managed Business Email infrastructure, if separate from the production VPS: infrastructure operator, datacentre/region, backup provider and processing region. If the email service is self-hosted on the same VPS, this entry can be removed.", "Resend processing region and DPA status, confirmed from the production Resend dashboard rather than the repository.", "Any additional subprocessor added after this audit date: update this list and, where ScaleSmiths acts as processor, notify affected clients under the applicable DPA change process."] },
    { title: "Not applicable", bullets: ["No online payment provider is active; the public site does not collect or process card details. Stripe appears only as a Forge integration placeholder and has no API integration, SDK or configuration.", "All experience analytics are self-hosted first-party events stored in the application database. No third-party analytics SDK is loaded in production.", "No Calendly, Cloudinary, HubSpot, or other externally hosted service widget is loaded by application code."] },
    { title: "Changes", paragraphs: ["Where ScaleSmiths acts as processor, clients will receive the notice or objection opportunity required by the applicable signed DPA before a material new subprocessor is used. An objection must concern a reasonable data-protection ground and the parties will work in good faith on a practical solution."] }, commonChanges,
  ] },
  cancellations: { title: "Cancellation & Refund Policy", introduction: "How requests to end bespoke projects and recurring B2B services are handled without inventing notice periods or refund rules.", sections: [
    { title: "Bespoke projects", paragraphs: ["The signed proposal governs cancellation, completed work, committed third-party costs, handover and any refund. If it is silent, the parties should agree a fair close-out based on work properly performed and unavoidable commitments; this page does not invent a deposit forfeiture or termination fee."] },
    { title: "Digital Growth Partnerships, hosting and managed email", paragraphs: ["Notice, billing interval, minimum commitment, cancellation effective date and refund treatment must be shown before order and recorded in the order. Until those commercial terms are confirmed, request cancellation at the contact address and ScaleSmiths will confirm the contractual position and safe offboarding steps. Email customers must migrate/export required mail before service ends."] },
    { title: "Business and consumer rights", paragraphs: ["Services are intended primarily for business customers. A business-use confirmation cannot remove genuine consumer status. If a consumer transaction is accepted, mandatory pre-contract information, cancellation, service-quality and refund rights apply and nothing here limits them. The future DMCC subscription-contract regime is not described as currently commenced; recurring UX must be reviewed before launch and again before that regime takes effect."] }, commonChanges,
  ] },
  complaints: { title: "Complaints Policy", introduction: "A clear route for concerns about ScaleSmiths services, billing, privacy or conduct.", sections: [
    { title: "Making a complaint", paragraphs: [`Email ${legalEntity.complaintsEmail} with your name, business, affected service, relevant dates, desired outcome and any safe supporting material. Do not email passwords or unnecessary sensitive information.`] },
    { title: "What happens next", paragraphs: ["ScaleSmiths will acknowledge the complaint within a reasonable period, identify an appropriate investigator, review relevant records and provide a reasoned response. Complex or security-sensitive matters may require interim updates. If unresolved, ask for founder-level review. No ombudsman, ADR membership or regulator affiliation is claimed; statutory complaint routes remain available where applicable."] }, commonChanges,
  ] },
  security: { title: "Security & Responsible Disclosure", introduction: "How to report a vulnerability, accidental exposure or account-security concern safely.", sections: [
    { title: "Reporting", paragraphs: [`Send a concise report to ${legalEntity.securityEmail}, including the affected URL, observed behaviour, impact and safe reproduction steps. Do not include live credentials or unnecessary personal data. ScaleSmiths does not currently offer a bug bounty.`] },
    { title: "Safe research", paragraphs: ["Do not access other users' data, maintain persistence, use denial-of-service techniques, send spam, exploit beyond the minimum needed to demonstrate risk, or disclose publicly before ScaleSmiths has had reasonable time to investigate. Good-faith reports will be assessed and acknowledged where contact details are supplied, but no fixed resolution time is guaranteed."] },
    { title: "Incidents", paragraphs: ["ScaleSmiths assesses security events under its incident process and notifies controllers, affected parties or regulators according to the applicable role and legal threshold. Public electronic communications obligations may create separate PECR reporting, customer notification and breach-log duties for managed email; those are operational requirements, not satisfied merely by this page."] }, commonChanges,
  ] },
  accessibility: { title: "Accessibility Statement", introduction: "ScaleSmiths aims to make its public website and service journeys usable by as many people as reasonably possible.", sections: [
    { title: "Current approach", paragraphs: ["The site uses semantic structure, keyboard-operable controls, visible focus, responsive layouts and reduced-motion support. ScaleSmiths does not claim audited conformance with a particular WCAG level unless a current formal assessment supports it."] },
    { title: "Report a problem", paragraphs: [`Email ${contact} with the page, task and assistive technology or browser involved where useful. ScaleSmiths will assess practical fixes and can discuss an alternative way to access information.`] }, commonChanges,
  ] },
}
