import "server-only"
import { and, asc, desc, eq, isNotNull, ne } from "drizzle-orm"
import { db } from "./db"
import { invoicePortalAccessEvents, invoicePortalClients, portalInvoiceItems, portalInvoices } from "./schema"
import { isPortalInvoiceStatus, type PortalInvoiceStatus } from "./invoice-status"

export interface PortalInvoiceDto { invoiceNumber:string;invoiceDate:string;dueDate:string;issuedDate:string|null;paidDate:string|null;voidedDate:string|null;status:PortalInvoiceStatus;customerName:string;customerContact:string|null;customerEmail:string|null;customerAddress:string[];supplier:Record<string,string|null>;payment:Record<string,string|null>;customerNote:string|null;items:Array<{title:string;description:string|null;quantity:number;unitAmount:number;lineAmount:number}>;subtotal:number;total:number;currency:"GBP" }
export async function listPortalInvoices(portalClientId:string){const rows=await db.select({invoiceNumber:portalInvoices.invoiceNumber,projectId:portalInvoices.projectId,invoiceDate:portalInvoices.invoiceDate,dueDate:portalInvoices.dueDate,status:portalInvoices.status,total:portalInvoices.total,paidAt:portalInvoices.paidAt}).from(portalInvoices).innerJoin(invoicePortalClients,eq(portalInvoices.clientId,invoicePortalClients.id)).where(and(eq(invoicePortalClients.portalClientId,portalClientId),isNotNull(portalInvoices.portalPublishedAt),ne(portalInvoices.status,"draft"))).orderBy(desc(portalInvoices.invoiceDate));return rows.filter((row):row is typeof row & {invoiceNumber:string;status:PortalInvoiceStatus}=>Boolean(row.invoiceNumber)&&isPortalInvoiceStatus(row.status)).map(row=>({invoiceNumber:row.invoiceNumber,projectId:row.projectId,invoiceDate:iso(row.invoiceDate),dueDate:iso(row.dueDate),status:row.status,total:row.total,paidAt:row.paidAt?.toISOString()??null}))}
export async function loadPortalInvoice(portalClientId:string,invoiceNumber:string):Promise<PortalInvoiceDto|null>{const [row]=await db.select().from(portalInvoices).innerJoin(invoicePortalClients,eq(portalInvoices.clientId,invoicePortalClients.id)).where(and(eq(invoicePortalClients.portalClientId,portalClientId),eq(portalInvoices.invoiceNumber,invoiceNumber),isNotNull(portalInvoices.portalPublishedAt))).limit(1);if(!row)return null;const invoice=row.invoices;const status=invoice.status;const number=invoice.invoiceNumber;if(!isPortalInvoiceStatus(status)||!invoice.portalPublishedAt||!number)return null;const items=await db.select({title:portalInvoiceItems.title,description:portalInvoiceItems.description,quantity:portalInvoiceItems.quantity,unitAmount:portalInvoiceItems.unitAmount,lineAmount:portalInvoiceItems.lineAmount}).from(portalInvoiceItems).where(eq(portalInvoiceItems.invoiceId,invoice.id)).orderBy(asc(portalInvoiceItems.position));return{invoiceNumber:number,invoiceDate:iso(invoice.invoiceDate),dueDate:iso(invoice.dueDate),issuedDate:invoice.issuedAt?.toISOString()??null,paidDate:invoice.paidAt?.toISOString()??null,voidedDate:invoice.voidedAt?.toISOString()??null,status,customerName:invoice.clientNameSnapshot,customerContact:invoice.billingContactNameSnapshot,customerEmail:invoice.billingEmailSnapshot,customerAddress:[invoice.billingAddressLine1Snapshot,invoice.billingAddressLine2Snapshot,invoice.billingCitySnapshot,invoice.billingCountySnapshot,invoice.billingPostcodeSnapshot,invoice.billingCountrySnapshot].filter((v):v is string=>Boolean(v)),supplier:invoice.supplierSnapshot??{},payment:invoice.paymentSnapshot??{},customerNote:invoice.customerNotes,items,subtotal:invoice.subtotal,total:invoice.total,currency:"GBP"}}
function iso(value:Date){return value.toISOString().slice(0,10)}
export async function recordPortalInvoiceAccess(portalClientId:string,invoiceNumber:string,accessType:"view"|"download"){const [row]=await db.select({id:portalInvoices.id}).from(portalInvoices).innerJoin(invoicePortalClients,eq(portalInvoices.clientId,invoicePortalClients.id)).where(and(eq(invoicePortalClients.portalClientId,portalClientId),eq(portalInvoices.invoiceNumber,invoiceNumber),isNotNull(portalInvoices.portalPublishedAt))).limit(1);if(!row)return false;await db.insert(invoicePortalAccessEvents).values({invoiceId:row.id,portalClientId,accessType});return true}
export async function loadPortalInvoicePdf(portalClientId:string,invoiceNumber:string){const [row]=await db.select({id:portalInvoices.id,pdf:portalInvoices.documentPdf}).from(portalInvoices).innerJoin(invoicePortalClients,eq(portalInvoices.clientId,invoicePortalClients.id)).where(and(eq(invoicePortalClients.portalClientId,portalClientId),eq(portalInvoices.invoiceNumber,invoiceNumber),isNotNull(portalInvoices.portalPublishedAt),ne(portalInvoices.status,"draft"))).limit(1);return row?.pdf?{invoiceId:row.id,pdf:Buffer.from(row.pdf)}:null}
