export interface EconomicsUsageRow { projectId:number|null; projectName:string; clientId:number|null; clientName:string|null; stage:string|null; provider:string; model:string; cost:number; tokens:number; completedAt:string; retries:number; latencyMs:number|null; fallback:boolean }
export function summarizeForgeEconomics(rows: EconomicsUsageRow[], counts: { completedWebsites:number; approvedArtifacts:number; proposals:number; estimatedRevenue:number }) {
  const totalCost = sum(rows.map((row) => row.cost)), totalTokens = sum(rows.map((row) => row.tokens)), retries = sum(rows.map((row) => row.retries)), fallbackCalls = rows.filter((row) => row.fallback).length
  const latencies = rows.map((row) => row.latencyMs).filter((value): value is number => value !== null)
  const group = (key: (row: EconomicsUsageRow) => string) => [...rows.reduce((map, row) => map.set(key(row), (map.get(key(row)) ?? 0) + row.cost), new Map<string, number>())].map(([label, cost]) => ({ label, cost:round(cost) })).sort((a,b) => b.cost-a.cost)
  const retryCost = sum(rows.map((row) => row.retries > 0 ? row.cost * row.retries / (row.retries + 1) : 0))
  return { totalCost:round(totalCost), totalTokens, retryCost:round(retryCost), fallbackRate:rows.length ? fallbackCalls/rows.length : 0, averageLatencyMs:latencies.length ? Math.round(sum(latencies)/latencies.length) : null, costPerCompletedWebsite:unit(totalCost, counts.completedWebsites), costPerApprovedArtifact:unit(totalCost, counts.approvedArtifacts), costPerProposal:unit(totalCost, counts.proposals), estimatedRevenue:counts.estimatedRevenue, estimatedGrossMarginImpact:counts.estimatedRevenue-totalCost, byProject:group((r)=>r.projectName), byClient:group((r)=>r.clientName ?? "Unassigned"), byStage:group((r)=>r.stage ?? "Unassigned"), byProvider:group((r)=>r.provider), byModel:group((r)=>r.model), byDay:group((r)=>r.completedAt.slice(0,10)), byWeek:group((r)=>weekKey(r.completedAt)), byMonth:group((r)=>r.completedAt.slice(0,7)), retries, calls:rows.length }
}
export function detectEconomicsSpikes(daily: Array<{label:string;cost:number}>) { if (daily.length < 2) return []; const baseline = sum(daily.slice(1).map((x)=>x.cost))/Math.max(1,daily.length-1); return daily.filter((x,index)=>index===0 && baseline>0 && x.cost>baseline*2).map((x)=>`Estimated AI cost on ${x.label} is more than 2x the recent daily average.`) }
function unit(cost:number,count:number){return count>0?round(cost/count):null} function sum(values:number[]){return values.reduce((a,b)=>a+b,0)} function round(value:number){return Number(value.toFixed(6))}
function weekKey(value:string){const date=new Date(value),day=(date.getUTCDay()+6)%7;date.setUTCDate(date.getUTCDate()-day);return `${date.toISOString().slice(0,10)} week`}
