import { describe,expect,it } from "vitest"
import { buildInvoiceEmail,validInvoiceRecipient } from "./invoice-delivery"
import type { InvoiceDocumentData } from "./invoice-document"
describe("invoice delivery content",()=>{
 it("builds customer-safe invoice mail without internal notes",()=>{const content=buildInvoiceEmail(fixture(),"invoice","https://scalesmiths.co.uk/portal");expect(content.subject).toBe("Invoice SS-CAK-0001 from ScaleSmiths");expect(content.text).toContain("£350.00");expect(content.text).toContain("SS-CAK-0001");expect(content.text).toContain("https://scalesmiths.co.uk/portal");expect(content.text).not.toContain("INTERNAL SECRET")})
 it("builds a distinct reminder without changing document data",()=>{const document=fixture();const content=buildInvoiceEmail(document,"reminder",null);expect(content.subject).toBe("Payment reminder: SS-CAK-0001");expect(document.documentState).toBe("issued")})
 it("validates and normalizes explicit recipients",()=>{expect(validInvoiceRecipient(" Billing@Example.COM ")).toBe("billing@example.com");expect(validInvoiceRecipient("bad")).toBeNull()})
})
function fixture():InvoiceDocumentData{return{templateVersion:"scalesmiths-v1",documentState:"issued",invoiceNumber:"SS-CAK-0001",invoiceDate:"2026-08-16",dueDate:"2026-08-30",issuedDate:"2026-08-16",paidDate:null,supplier:{legalName:"ScaleSmiths",tradingName:null,addressLine1:"1 Road",addressLine2:null,city:"Leeds",county:null,postcode:"LS1",country:"UK",contactEmail:null,website:null,companyNumber:null,vatNumber:null},customer:{businessName:"Confirm-a-Kill",contactName:"Casey",email:"billing@example.com",addressLine1:"2 Road",addressLine2:null,city:"York",county:null,postcode:"YO1",country:"UK"},payment:{instructions:"Pay by bank transfer.",accountName:null,sortCode:null,accountNumber:null,referenceInstructions:"Use the invoice number."},customerNote:"Customer note",items:[{title:"Retainer",description:null,quantity:1,unitAmount:35000,lineAmount:35000}],subtotal:35000,total:35000,currency:"GBP"}}
