CREATE TYPE "public"."client_document_type" AS ENUM('brief', 'proposal', 'contract', 'brand_asset', 'content', 'design', 'staging_link', 'launch_checklist', 'handoff', 'report', 'technical', 'other');--> statement-breakpoint
CREATE TYPE "public"."client_document_source" AS ENUM('upload', 'link');--> statement-breakpoint
CREATE TYPE "public"."client_document_storage_provider" AS ENUM('r2', 'external');--> statement-breakpoint
CREATE TABLE "client_documents" ("id" serial PRIMARY KEY NOT NULL, "client_id" integer NOT NULL, "project_id" integer NOT NULL, "deliverable_id" integer, "document_type" "client_document_type" NOT NULL, "source" "client_document_source" NOT NULL, "title" text NOT NULL, "description" text, "original_filename" text, "storage_provider" "client_document_storage_provider" NOT NULL, "storage_key" text NOT NULL, "visibility" "request_message_visibility" DEFAULT 'internal' NOT NULL, "uploaded_by" uuid, "version" integer DEFAULT 1 NOT NULL, "checksum_sha256" text, "mime_type" text, "size_bytes" integer, "archived_at" timestamp with time zone, "created_at" timestamp with time zone DEFAULT now() NOT NULL, "updated_at" timestamp with time zone DEFAULT now() NOT NULL, CONSTRAINT "client_documents_version_check" CHECK ("version" > 0), CONSTRAINT "client_documents_size_check" CHECK ("size_bytes" is null or "size_bytes" >= 0), CONSTRAINT "client_documents_source_metadata_check" CHECK (("source" = 'upload' and "storage_provider" = 'r2' and "original_filename" is not null and "checksum_sha256" is not null and "mime_type" is not null and "size_bytes" is not null) or ("source" = 'link' and "storage_provider" = 'external' and "checksum_sha256" is null and "size_bytes" is null)));--> statement-breakpoint
CREATE TABLE "client_document_access_events" ("id" serial PRIMARY KEY NOT NULL, "document_id" integer NOT NULL, "portal_client_id" text NOT NULL, "action" text NOT NULL, "created_at" timestamp with time zone DEFAULT now() NOT NULL);--> statement-breakpoint
ALTER TABLE "client_documents" ADD CONSTRAINT "client_documents_client_id_clients_id_fk" FOREIGN KEY ("client_id") REFERENCES "public"."clients"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "client_documents" ADD CONSTRAINT "client_documents_project_id_delivery_projects_id_fk" FOREIGN KEY ("project_id") REFERENCES "public"."delivery_projects"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "client_documents" ADD CONSTRAINT "client_documents_deliverable_id_delivery_deliverables_id_fk" FOREIGN KEY ("deliverable_id") REFERENCES "public"."delivery_deliverables"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "client_documents" ADD CONSTRAINT "client_documents_uploaded_by_admin_users_id_fk" FOREIGN KEY ("uploaded_by") REFERENCES "public"."admin_users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "client_document_access_events" ADD CONSTRAINT "client_document_access_events_document_id_client_documents_id_fk" FOREIGN KEY ("document_id") REFERENCES "public"."client_documents"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "client_documents_client_project_idx" ON "client_documents" USING btree ("client_id","project_id","created_at");--> statement-breakpoint
CREATE INDEX "client_documents_project_visibility_idx" ON "client_documents" USING btree ("project_id","visibility","archived_at");--> statement-breakpoint
CREATE UNIQUE INDEX "client_documents_storage_key_idx" ON "client_documents" USING btree ("storage_provider","storage_key");--> statement-breakpoint
CREATE INDEX "client_document_access_document_idx" ON "client_document_access_events" USING btree ("document_id","created_at");--> statement-breakpoint
INSERT INTO "client_documents" ("client_id", "project_id", "deliverable_id", "document_type", "source", "title", "storage_provider", "storage_key", "visibility", "uploaded_by", "version", "created_at", "updated_at") SELECT p."client_id", r."project_id", r."deliverable_id", 'other', 'link', r."title", 'external', r."url", r."visibility", r."created_by", 1, r."created_at", r."created_at" FROM "delivery_resources" r INNER JOIN "delivery_projects" p ON p."id" = r."project_id" WHERE r."url" LIKE 'https://%';
