import { NextResponse } from "next/server"
import { auth } from "../../../../../../../auth"
import { guardApiCapability } from "@/lib/server/rbac"
import { approveForgeMigrationExecution, rollbackForgeMigrationCandidate } from "@/lib/server/forge-migration-execution-agent"
import { enqueueForgeJob, forgeJobResponseBody } from "@/lib/server/forge-job-runner"
export const dynamic = "force-dynamic"
export const runtime = "nodejs"
function projectIdOf(value: string) { const id = Number(value); return Number.isInteger(id) && id > 0 ? id : null }
export async function POST(_request: Request, { params }: { params: Promise<{ id: string }> }) { const session = await auth(); if (!session) return NextResponse.json({ error: "Unauthorized." }, { status: 401 }); const projectId = projectIdOf((await params).id); if (!projectId) return NextResponse.json({ error: "Invalid Forge project id." }, { status: 400 }); try { await guardApiCapability("forge.execute"); const actor = session.user?.email ?? session.user?.name ?? "admin"; return NextResponse.json(forgeJobResponseBody(await enqueueForgeJob({ projectId, kind: "migration_execution", actor }))) } catch { return NextResponse.json({ error: "Unable to create migration candidate." }, { status: 500 }) } }
export async function PATCH(request: Request, { params }: { params: Promise<{ id: string }> }) { const session = await auth(); if (!session) return NextResponse.json({ error: "Unauthorized." }, { status: 401 }); const projectId = projectIdOf((await params).id); if (!projectId) return NextResponse.json({ error: "Invalid Forge project id." }, { status: 400 }); try { const body = await request.json() as { artifactId?: unknown; action?: unknown; reason?: unknown }; if (!Number.isInteger(body.artifactId) || typeof body.reason !== "string") return NextResponse.json({ error: "Artifact id and reason are required." }, { status: 400 }); const actor = session.user?.email ?? session.user?.name ?? "admin"; if (body.action === "rollback") { await guardApiCapability("forge.approve"); return NextResponse.json(await rollbackForgeMigrationCandidate(projectId, Number(body.artifactId), actor, body.reason)) } if (body.action !== "redirect_export" && body.action !== "deployment") return NextResponse.json({ error: "Invalid migration action." }, { status: 400 }); await guardApiCapability(body.action === "deployment" ? "deployments.execute" : "forge.approve"); return NextResponse.json(await approveForgeMigrationExecution(projectId, Number(body.artifactId), actor, body.action, body.reason)) } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : "Unable to update migration candidate." }, { status: 409 }) } }
