import {afterAll,beforeAll,beforeEach,describe,expect,it} from "vitest"
import {Pool} from "pg"
import {drizzle} from "drizzle-orm/node-postgres"
import {migrate} from "drizzle-orm/node-postgres/migrator"
import path from "node:path"
import {promisify} from "node:util"
import {execFile} from "node:child_process"
import bcrypt from "bcryptjs"
import {getTableName,is} from "drizzle-orm"
import {PgTable} from "drizzle-orm/pg-core"
import * as currentSchema from "../../src/lib/schema"
import {assertSafeIntegrationDatabaseUrl} from "../../src/lib/test-database-safety"

const run=promisify(execFile);let pool:Pool;let url:string;let webUrl:string;let adminUrl:string;let migrationUrl:string
beforeAll(async()=>{
  url=assertSafeIntegrationDatabaseUrl(process.env.TEST_DATABASE_URL)
  webUrl=roleUrl(url,"ss_test_web","web-password")
  adminUrl=roleUrl(url,"ss_test_admin","admin-password")
  migrationUrl=roleUrl(url,"ss_test_migration","migration-password")
  process.env.DATABASE_URL=url
  process.env.ADMIN_DATABASE_URL=adminUrl
  process.env.MIGRATION_DATABASE_URL=migrationUrl
  process.env.NODE_ENV="test"
  pool=new Pool({connectionString:url,max:8})
  await pool.query("DROP SCHEMA IF EXISTS drizzle CASCADE; DROP SCHEMA IF EXISTS public CASCADE; CREATE SCHEMA public")
  const provisionEnv={...process.env,POSTGRES_PROVISIONING_DATABASE_URL:url,WEB_DATABASE_URL:webUrl,ADMIN_DATABASE_URL:adminUrl,MIGRATION_DATABASE_URL:migrationUrl,READONLY_DATABASE_URL:roleUrl(url,"ss_test_readonly","readonly-password")}
  await run(process.execPath,[path.resolve("scripts/provision-postgres-roles.mjs"),"--confirm-provision"],{env:provisionEnv})
  const migrationPool=new Pool({connectionString:migrationUrl,max:2})
  try {
    const database=drizzle(migrationPool)
    await migrate(database,{migrationsFolder:path.resolve("../web/drizzle"),migrationsTable:"__drizzle_web_migrations",migrationsSchema:"drizzle"})
    await migrate(database,{migrationsFolder:path.resolve("drizzle")})
  } finally { await migrationPool.end() }
  await run(process.execPath,[path.resolve("scripts/provision-postgres-roles.mjs"),"--confirm-provision"],{env:provisionEnv})
})
beforeEach(async()=>{const tables=await pool.query<{tablename:string}>("SELECT tablename FROM pg_tables WHERE schemaname='public' AND tablename <> '__drizzle_migrations'");if(tables.rows.length)await pool.query(`TRUNCATE ${tables.rows.map(r=>`"public"."${r.tablename.replaceAll('"','""')}"`).join(",")} RESTART IDENTITY CASCADE`)})
afterAll(async()=>{await pool?.end()})

describe("real PostgreSQL integration",()=>{
  it("applies web then admin migration histories as the migration owner",async()=>{const result=await pool.query("SELECT c.relname,r.rolname owner FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace JOIN pg_roles r ON r.oid=c.relowner WHERE n.nspname IN ('public','drizzle') AND c.relname IN ('quote_requests','admin_users','__drizzle_web_migrations','__drizzle_migrations')");expect(result.rows).toHaveLength(4);expect(result.rows.every(row=>row.owner==="ss_test_migration")).toBe(true)})

  it("prevents web credentials reading admin data or modifying schema",async()=>{const webPool=new Pool({connectionString:webUrl});try{await expect(webPool.query("SELECT * FROM admin_users")).rejects.toMatchObject({code:"42501"});await expect(webPool.query("CREATE TABLE web_escape(id integer)")).rejects.toMatchObject({code:"42501"});await expect(webPool.query("INSERT INTO quote_requests(name,email,brief) VALUES('Web','web@example.test','Allowed public insert')")).resolves.toMatchObject({rowCount:1})}finally{await webPool.end()}})

  it("exposes only evidenced, verified and in-date claims through the web role",async()=>{await pool.query("INSERT INTO public_claims(id,approved_wording,claim_type,source_name,permitted_routes,permitted_components) VALUES('fixture.testimonial','A draft attributed quote','testimonial','Fixture Client',ARRAY['/'],ARRAY['testimonials'])");const webPool=new Pool({connectionString:webUrl});try{await expect(webPool.query("SELECT * FROM public_claims")).rejects.toMatchObject({code:"42501"});await expect(webPool.query("SELECT * FROM public_claim_evidence")).rejects.toMatchObject({code:"42501"});expect((await webPool.query("SELECT * FROM public_verified_claims")).rowCount).toBe(0);await pool.query("UPDATE public_claims SET status='verified',client_approval_status='approved',verified_by='raw-update',verified_at=now(),review_expires_at=now()+interval '1 day' WHERE id='fixture.testimonial'");expect((await webPool.query("SELECT * FROM public_verified_claims")).rowCount).toBe(0);await pool.query("UPDATE public_claims SET status='draft',client_approval_status='pending',verified_by=NULL,verified_at=NULL,review_expires_at=NULL WHERE id='fixture.testimonial'");const {updatePublicClaim}=await import("../../src/lib/server/public-claims");await updatePublicClaim("fixture.testimonial",{approvedWording:"An approved attributed quote",claimType:"testimonial",sourceName:"Fixture Client",attributionName:"Fixture Person",attributionBusiness:"Fixture Client",clientApprovalStatus:"approved",status:"verified",reviewExpiresAt:new Date(Date.now()+86_400_000),permittedRoutes:["/"],permittedComponents:["testimonials"],evidenceDescription:"Signed approval held by operations",evidenceReference:"private://claims/fixture",reason:"Evidence and client wording checked"},"integration-owner");const visible=await webPool.query("SELECT * FROM public_verified_claims");expect(visible.rows).toHaveLength(1);expect(visible.rows[0]).toMatchObject({id:"fixture.testimonial",approved_wording:"An approved attributed quote",attribution_name:"Fixture Person"});expect(Object.keys(visible.rows[0])).not.toContain("evidence_reference");expect(Object.keys(visible.rows[0])).not.toContain("verified_by");expect((await pool.query("SELECT action,previous_status,new_status FROM public_claim_audit_logs WHERE claim_id='fixture.testimonial'")).rows).toEqual([{action:"claim_status_changed",previous_status:"draft",new_status:"verified"}])}finally{await webPool.end()}})

  it("prevents admin runtime credentials applying migrations or owning schema",async()=>{const adminPool=new Pool({connectionString:adminUrl});try{await expect(adminPool.query("CREATE TABLE admin_escape(id integer)")).rejects.toMatchObject({code:"42501"});await expect(adminPool.query("INSERT INTO drizzle.__drizzle_migrations(hash,created_at) VALUES('forged',0)")).rejects.toMatchObject({code:"42501"});const owner=await pool.query("SELECT r.rolname FROM pg_namespace n JOIN pg_roles r ON r.oid=n.nspowner WHERE n.nspname='public'");expect(owner.rows[0].rolname).toBe("ss_test_migration")}finally{await adminPool.end()}})

  it("enforces client analytics tenant isolation with RLS",async()=>{const protectedTables=["client_analytics_configs","client_analytics_daily_metrics","client_analytics_audit_logs","client_optimisation_proposals"];const rls=await pool.query("SELECT c.relname,c.relrowsecurity,c.relforcerowsecurity,count(p.policyname)::int policies FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace LEFT JOIN pg_policies p ON p.schemaname=n.nspname AND p.tablename=c.relname WHERE n.nspname='public' AND c.relname=ANY($1::text[]) GROUP BY c.relname,c.relrowsecurity,c.relforcerowsecurity",[protectedTables]);expect(rls.rows).toHaveLength(protectedTables.length);expect(rls.rows.every(row=>row.relrowsecurity&&row.relforcerowsecurity&&row.policies===1)).toBe(true);const first=(await pool.query("INSERT INTO clients(name) VALUES('Tenant A') RETURNING id")).rows[0].id;const second=(await pool.query("INSERT INTO clients(name) VALUES('Tenant B') RETURNING id")).rows[0].id;await pool.query("INSERT INTO client_analytics_configs(client_id,provider,display_name,source_attribution,created_by) VALUES($1,'manual','A','fixture','test'),($2,'manual','B','fixture','test')",[first,second]);const adminPool=new Pool({connectionString:adminUrl});try{expect((await adminPool.query("SELECT * FROM client_analytics_configs")).rowCount).toBe(0);const client=await adminPool.connect();try{await client.query("BEGIN");await client.query("SELECT set_config('app.current_client_id',$1,true)",[String(first)]);const visible=await client.query("SELECT client_id FROM client_analytics_configs ORDER BY client_id");expect(visible.rows).toEqual([{client_id:first}]);await expect(client.query("INSERT INTO client_analytics_configs(client_id,provider,display_name,source_attribution,created_by) VALUES($1,'manual','Cross tenant','fixture','test')",[second])).rejects.toMatchObject({code:"42501"});await client.query("ROLLBACK")}finally{client.release()}}finally{await adminPool.end()}})

  it("migrates an empty database and matches the current Drizzle table surface",async()=>{const migrations=await pool.query("SELECT count(*)::int count FROM drizzle.__drizzle_migrations");expect(migrations.rows[0].count).toBeGreaterThan(20);const actualTables=new Set((await pool.query<{tablename:string}>("SELECT tablename FROM pg_tables WHERE schemaname='public'")).rows.map(r=>r.tablename));const expectedTables=Object.values(currentSchema).filter((value):value is PgTable=>is(value,PgTable)).map(getTableName);expect([...expectedTables].filter(name=>!actualTables.has(name))).toEqual([]);const columns=await pool.query<{table_name:string,column_name:string}>("SELECT table_name,column_name FROM information_schema.columns WHERE table_schema='public'");const names=new Set(columns.rows.map(r=>`${r.table_name}.${r.column_name}`));for(const expected of ["admin_users.session_version","forge_tasks.result_quality","forge_artifacts.output_hash","forge_ai_budget_reservations.idempotency_key","forge_activity_logs.metadata_json","forge_runs.policy_json","forge_run_steps.output_artifact_ids","forge_run_events.event_type","forge_worker_heartbeats.last_heartbeat_at"])expect(names.has(expected)).toBe(true)})

  it("bootstraps one persistent owner idempotently and authenticates it",async()=>{const env={...process.env,ADMIN_DATABASE_URL:adminUrl,ADMIN_EMAIL:"integration-owner@example.test",ADMIN_PASSWORD:"integration-password-123",ADMIN_DISPLAY_NAME:"Integration Owner"};await run(process.execPath,[path.resolve("scripts/bootstrap-admin.mjs")],{env});await run(process.execPath,[path.resolve("scripts/bootstrap-admin.mjs")],{env});const rows=await pool.query("SELECT * FROM admin_users");expect(rows.rowCount).toBe(1);const {authenticateAdminUser}=await import("../../src/lib/server/admin-users");const user=await authenticateAdminUser("integration-owner@example.test","integration-password-123");expect(user).toMatchObject({role:"owner",active:true});expect(await bcrypt.compare("integration-password-123",rows.rows[0].password_hash)).toBe(true)})

  it("persists RBAC roles and enforces direct-request capabilities",async()=>{const hash=await bcrypt.hash("password-password",4);await pool.query("INSERT INTO admin_users(email,display_name,password_hash,role) VALUES('viewer@example.test','Viewer',$1,'viewer')",[hash]);const {authorizeRequest}=await import("../../src/lib/rbac");const persisted=await pool.query("SELECT role FROM admin_users WHERE email='viewer@example.test'");expect(authorizeRequest(persisted.rows[0].role,{pathname:"/api/forge/projects/1/deploy",method:"POST"})).toMatchObject({allowed:false,capability:"deployments.execute"})})

  it("creates Forge projects and keeps execution status separate from result quality",async()=>{const project=await createProject();const task=await pool.query("INSERT INTO forge_tasks(project_id,title,agent_type,status,result_quality,downstream_allowed,publication_blocked) VALUES($1,'Generate','frontend','completed','fallback',true,true) RETURNING *",[project]);expect(task.rows[0]).toMatchObject({status:"completed",result_quality:"fallback",publication_blocked:true});await pool.query("INSERT INTO forge_activity_logs(project_id,actor,action,message,metadata_json) VALUES($1,'tester','task_completed','Completed with fallback',$2)",[project,{taskId:task.rows[0].id}]);expect((await pool.query("SELECT metadata_json FROM forge_activity_logs")).rows[0].metadata_json.taskId).toBe(task.rows[0].id)})

  it("creates immutable artifact lineage and approval transitions",async()=>{const project=await createProject();const task=(await pool.query("INSERT INTO forge_tasks(project_id,title,agent_type,status) VALUES($1,'Copy','copy','completed') RETURNING id",[project])).rows[0].id;const {saveVersionedForgeArtifact}=await import("../../src/lib/server/forge-artifacts");const base={projectId:project,type:"copy_doc" as const,title:"Copy",actor:"reviewer",provenance:{sourceTaskId:task,promptVersion:"1.0.0",schemaVersion:"1.0.0",inputContext:{brief:"a"},qualityState:"requires_review" as const}};const first=await saveVersionedForgeArtifact({...base,content:"v1",metadataJson:{status:"draft"}});const second=await saveVersionedForgeArtifact({...base,content:"v2",metadataJson:{status:"draft"}});expect(second).toMatchObject({version:2,parentArtifactId:first.id});expect((await pool.query("SELECT superseded_at FROM forge_artifacts WHERE id=$1",[first.id])).rows[0].superseded_at).not.toBeNull();await pool.query("UPDATE forge_artifacts SET approval_state='approved',approval_history=$2::jsonb WHERE id=$1",[second.id,JSON.stringify([{actor:"reviewer",reason:"Compared with approved brief"}])]);expect((await pool.query("SELECT approval_state,approval_history FROM forge_artifacts WHERE id=$1",[second.id])).rows[0]).toMatchObject({approval_state:"approved",approval_history:[{actor:"reviewer",reason:"Compared with approved brief"}]})})

  it("atomically reserves budget under concurrent writes and reconciles usage",async()=>{const project=await createProject();const tasks=await Promise.all(["A","B"].map(async title=>(await pool.query("INSERT INTO forge_tasks(project_id,title,agent_type) VALUES($1,$2,'copy') RETURNING id",[project,title])).rows[0].id));const {reserveForgeAiBudget,reconcileForgeAiBudget}=await import("../../src/lib/server/forge-budget-reservations");const env={FORGE_AI_DAILY_USD_BUDGET:"1",FORGE_MAX_PROJECT_AI_COST:"1"};const settled=await Promise.allSettled(tasks.map((task,index)=>reserveForgeAiBudget({projectId:project,taskId:task,provider:"openai",model:"test",estimatedMaxCost:.6,idempotencyKey:`concurrent-${index}`,env})));expect(settled.filter(x=>x.status==="fulfilled")).toHaveLength(1);const reservation=(settled.find(x=>x.status==="fulfilled") as PromiseFulfilledResult<Awaited<ReturnType<typeof reserveForgeAiBudget>>>).value;await reconcileForgeAiBudget({reservationId:reservation.id,actualCost:.2,usageKnown:true});const row=(await pool.query("SELECT status,reserved_cost,actual_cost FROM forge_ai_budget_reservations WHERE id=$1",[reservation.id])).rows[0];expect(row).toMatchObject({status:"reconciled",reserved_cost:"0.600000",actual_cost:"0.200000"})})

  it("adopts an existing project into one idempotent run and pauses at its human brief gate",async()=>{const project=await createProject();await insertArtifact(project,"handover_doc","brief-v1");const orchestration=await import("../../src/lib/server/forge-run-orchestrator");const first=await orchestration.createForgeRun({projectId:project,actor:"integration-owner"});const adopted=await orchestration.createForgeRun({projectId:project,actor:"integration-owner"});expect(adopted?.id).toBe(first?.id);expect((await pool.query("SELECT count(*)::int count FROM forge_runs WHERE project_id=$1",[project])).rows[0].count).toBe(1);const started=await orchestration.startForgeRun(first!.id,"integration-owner");expect(started?.status).toBe("paused");expect(started?.currentStage).toBe("brief");expect(started?.steps.find(step=>step.stage==="brief")?.status).toBe("awaiting_approval")})

  it("continues after approval, recovers idempotently, and propagates terminal job failure",async()=>{const project=await createProject();await insertArtifact(project,"handover_doc","brief-v1");const orchestration=await import("../../src/lib/server/forge-run-orchestrator");const run=await orchestration.createForgeRun({projectId:project,actor:"integration-owner"});await orchestration.startForgeRun(run!.id,"integration-owner");const approved=await orchestration.approveForgeRunStep(run!.id,"brief","integration-owner","Approved against the signed client brief.");const research=approved?.steps.find(step=>step.stage==="research");expect(research?.status).toBe("queued");expect(research?.attemptCount).toBe(1);await orchestration.recoverForgeRuns();await orchestration.recoverForgeRuns();expect((await pool.query("SELECT count(*)::int count FROM forge_jobs WHERE idempotency_key LIKE $1",[`forge-run:${run!.id}:%`])).rows[0].count).toBe(1);await pool.query("UPDATE forge_jobs SET status='failed',failure_reason='Provider terminal failure',attempts=max_attempts WHERE id=$1",[research!.jobId]);await orchestration.handleForgeRunJobOutcome(research!.jobId!,"failed","Provider terminal failure");const failed=await orchestration.loadForgeRun(run!.id);expect(failed?.status).toBe("failed");expect(failed?.steps.find(step=>step.stage==="research")).toMatchObject({status:"failed",failureCategory:"provider"});await orchestration.retryForgeRunStep(run!.id,"research","integration-owner");const retried=await orchestration.loadForgeRun(run!.id);expect(retried?.status).toBe("running");expect(retried?.steps.find(step=>step.stage==="research")?.attemptCount).toBe(2)})

  it("invalidates only recorded downstream outputs when an approved upstream artifact changes",async()=>{const project=await createProject();const brief=await insertArtifact(project,"handover_doc","brief-v1");const research=await insertArtifact(project,"research_report","research-v1");await insertArtifact(project,"sitemap","sitemap-v1");const orchestration=await import("../../src/lib/server/forge-run-orchestrator");const run=await orchestration.createForgeRun({projectId:project,actor:"integration-owner"});await orchestration.startForgeRun(run!.id,"integration-owner");await insertArtifact(project,"handover_doc","brief-v2");await orchestration.approveForgeRunStep(run!.id,"brief","integration-owner","Approved the revised client brief.");const stale=(await pool.query("SELECT id,superseded_at FROM forge_artifacts WHERE id=ANY($1::int[]) ORDER BY id",[[brief,research]])).rows;expect(stale.find(row=>row.id===brief)?.superseded_at).toBeNull();expect(stale.find(row=>row.id===research)?.superseded_at).not.toBeNull();const refreshed=await orchestration.loadForgeRun(run!.id);expect(refreshed?.steps.find(step=>step.stage==="research")?.status).toBe("queued")})

  it("pauses rather than fails when the next automatic stage exceeds budget",async()=>{const previous=process.env.FORGE_MAX_PROJECT_AI_COST;process.env.FORGE_MAX_PROJECT_AI_COST="0.01";try{const project=await createProject();await insertArtifact(project,"handover_doc","brief-v1");const orchestration=await import("../../src/lib/server/forge-run-orchestrator");const run=await orchestration.createForgeRun({projectId:project,actor:"integration-owner"});await orchestration.startForgeRun(run!.id,"integration-owner");const paused=await orchestration.approveForgeRunStep(run!.id,"brief","integration-owner","Approved against the signed client brief.");expect(paused?.status).toBe("paused");expect(paused?.pauseReason).toContain("budget is exhausted");expect(paused?.steps.find(step=>step.stage==="research")).toMatchObject({status:"blocked",failureCategory:"budget_exceeded"})}finally{if(previous===undefined)delete process.env.FORGE_MAX_PROJECT_AI_COST;else process.env.FORGE_MAX_PROJECT_AI_COST=previous}})

  it("approves unified intake, creates and starts one run, and deduplicates repeat submissions",async()=>{const {interpretForgeProjectIntake}=await import("../../src/lib/forge-project-intake");const {approveUnifiedForgeIntake}=await import("../../src/lib/server/forge-unified-intake");const interpretation=interpretForgeProjectIntake({request:"Build a premium lead-generation website for Acme Commercial Roofing in Nottingham with email and WhatsApp enquiries.",advanced:{businessName:"Acme Commercial Roofing"}});const payload={interpretation,summary:interpretation.summary,submissionKey:"integration-unified-intake-0001"};const first=await approveUnifiedForgeIntake(payload,"integration-owner");expect(first.status).toBe(201);const firstJson=await first.json();expect(firstJson.run.status).toBe("running");expect(firstJson.run.steps.find((step:{stage:string})=>step.stage==="brief").status).toBe("completed");expect(firstJson.redirectTo).toContain(`forge/${firstJson.project.id}`);const second=await approveUnifiedForgeIntake(payload,"integration-owner");expect(second.status).toBe(201);const secondJson=await second.json();expect(secondJson.project.id).toBe(firstJson.project.id);expect((await pool.query("SELECT count(*)::int count FROM forge_projects")).rows[0].count).toBe(1);expect((await pool.query("SELECT count(*)::int count FROM forge_runs")).rows[0].count).toBe(1)})

  it("rolls back all writes when a transaction fails",async()=>{const client=await pool.connect();try{await client.query("BEGIN");await client.query("INSERT INTO forge_projects(name,business_name) VALUES('Rollback','Rollback Ltd')");await client.query("INSERT INTO forge_tasks(project_id,title,agent_type) VALUES(999999,'Invalid','copy')");await client.query("COMMIT")}catch{await client.query("ROLLBACK")}finally{client.release()}expect((await pool.query("SELECT count(*)::int count FROM forge_projects WHERE name='Rollback'")).rows[0].count).toBe(0)})
})
async function createProject(){return (await pool.query("INSERT INTO forge_projects(name,business_name,status) VALUES('Integration Site','Integration Ltd','intake') RETURNING id")).rows[0].id as number}
async function insertArtifact(projectId:number,type:string,hash:string){return (await pool.query("INSERT INTO forge_artifacts(project_id,type,title,content,output_hash,quality_state,approval_state) VALUES($1,$2,'Integration artifact','{}',$3,'validated','approved') RETURNING id",[projectId,type,hash])).rows[0].id as number}
function roleUrl(base:string,username:string,password:string){const value=new URL(base);value.username=username;value.password=password;return value.toString()}
