import {afterAll,beforeAll,beforeEach,describe,expect,it} from "vitest"
import {Pool} from "pg"
import {drizzle} from "drizzle-orm/node-postgres"
import {migrate} from "drizzle-orm/node-postgres/migrator"
import path from "node:path"
import {promisify} from "node:util"
import {execFile} from "node:child_process"
import bcrypt from "bcryptjs"
import {getTableName,is} from "drizzle-orm"
import {PgTable} from "drizzle-orm/pg-core"
import * as currentSchema from "../../src/lib/schema"
import {assertSafeIntegrationDatabaseUrl} from "../../src/lib/test-database-safety"

const run=promisify(execFile);let pool:Pool;let url:string
beforeAll(async()=>{url=assertSafeIntegrationDatabaseUrl(process.env.TEST_DATABASE_URL);process.env.DATABASE_URL=url;process.env.NODE_ENV="test";pool=new Pool({connectionString:url,max:8});await pool.query("DROP SCHEMA IF EXISTS public CASCADE; CREATE SCHEMA public");const database=drizzle(pool);await migrate(database,{migrationsFolder:path.resolve("../web/drizzle"),migrationsTable:"__drizzle_web_migrations",migrationsSchema:"drizzle"});await migrate(database,{migrationsFolder:path.resolve("drizzle")})})
beforeEach(async()=>{const tables=await pool.query<{tablename:string}>("SELECT tablename FROM pg_tables WHERE schemaname='public' AND tablename <> '__drizzle_migrations'");if(tables.rows.length)await pool.query(`TRUNCATE ${tables.rows.map(r=>`"public"."${r.tablename.replaceAll('"','""')}"`).join(",")} RESTART IDENTITY CASCADE`)})
afterAll(async()=>{await pool?.end()})

describe("real PostgreSQL integration",()=>{
  it("migrates an empty database and matches the current Drizzle table surface",async()=>{const migrations=await pool.query("SELECT count(*)::int count FROM drizzle.__drizzle_migrations");expect(migrations.rows[0].count).toBeGreaterThan(20);const actualTables=new Set((await pool.query<{tablename:string}>("SELECT tablename FROM pg_tables WHERE schemaname='public'")).rows.map(r=>r.tablename));const expectedTables=Object.values(currentSchema).filter((value):value is PgTable=>is(value,PgTable)).map(getTableName);expect([...expectedTables].filter(name=>!actualTables.has(name))).toEqual([]);const columns=await pool.query<{table_name:string,column_name:string}>("SELECT table_name,column_name FROM information_schema.columns WHERE table_schema='public'");const names=new Set(columns.rows.map(r=>`${r.table_name}.${r.column_name}`));for(const expected of ["admin_users.session_version","forge_tasks.result_quality","forge_artifacts.output_hash","forge_ai_budget_reservations.idempotency_key","forge_activity_logs.metadata_json"])expect(names.has(expected)).toBe(true)})

  it("bootstraps one persistent owner idempotently and authenticates it",async()=>{const env={...process.env,DATABASE_URL:url,ADMIN_EMAIL:"integration-owner@example.test",ADMIN_PASSWORD:"integration-password-123",ADMIN_DISPLAY_NAME:"Integration Owner"};await run(process.execPath,[path.resolve("scripts/bootstrap-admin.mjs")],{env});await run(process.execPath,[path.resolve("scripts/bootstrap-admin.mjs")],{env});const rows=await pool.query("SELECT * FROM admin_users");expect(rows.rowCount).toBe(1);const {authenticateAdminUser}=await import("../../src/lib/server/admin-users");const user=await authenticateAdminUser("integration-owner@example.test","integration-password-123");expect(user).toMatchObject({role:"owner",active:true});expect(await bcrypt.compare("integration-password-123",rows.rows[0].password_hash)).toBe(true)})

  it("persists RBAC roles and enforces direct-request capabilities",async()=>{const hash=await bcrypt.hash("password-password",4);await pool.query("INSERT INTO admin_users(email,display_name,password_hash,role) VALUES('viewer@example.test','Viewer',$1,'viewer')",[hash]);const {authorizeRequest}=await import("../../src/lib/rbac");const persisted=await pool.query("SELECT role FROM admin_users WHERE email='viewer@example.test'");expect(authorizeRequest(persisted.rows[0].role,{pathname:"/api/forge/projects/1/deploy",method:"POST"})).toMatchObject({allowed:false,capability:"deployments.execute"})})

  it("creates Forge projects and keeps execution status separate from result quality",async()=>{const project=await createProject();const task=await pool.query("INSERT INTO forge_tasks(project_id,title,agent_type,status,result_quality,downstream_allowed,publication_blocked) VALUES($1,'Generate','frontend','completed','fallback',true,true) RETURNING *",[project]);expect(task.rows[0]).toMatchObject({status:"completed",result_quality:"fallback",publication_blocked:true});await pool.query("INSERT INTO forge_activity_logs(project_id,actor,action,message,metadata_json) VALUES($1,'tester','task_completed','Completed with fallback',$2)",[project,{taskId:task.rows[0].id}]);expect((await pool.query("SELECT metadata_json FROM forge_activity_logs")).rows[0].metadata_json.taskId).toBe(task.rows[0].id)})

  it("creates immutable artifact lineage and approval transitions",async()=>{const project=await createProject();const task=(await pool.query("INSERT INTO forge_tasks(project_id,title,agent_type,status) VALUES($1,'Copy','copy','completed') RETURNING id",[project])).rows[0].id;const {saveVersionedForgeArtifact}=await import("../../src/lib/server/forge-artifacts");const base={projectId:project,type:"copy_doc" as const,title:"Copy",actor:"reviewer",provenance:{sourceTaskId:task,promptVersion:"1.0.0",schemaVersion:"1.0.0",inputContext:{brief:"a"},qualityState:"requires_review" as const}};const first=await saveVersionedForgeArtifact({...base,content:"v1",metadataJson:{status:"draft"}});const second=await saveVersionedForgeArtifact({...base,content:"v2",metadataJson:{status:"draft"}});expect(second).toMatchObject({version:2,parentArtifactId:first.id});expect((await pool.query("SELECT superseded_at FROM forge_artifacts WHERE id=$1",[first.id])).rows[0].superseded_at).not.toBeNull();await pool.query("UPDATE forge_artifacts SET approval_state='approved',approval_history=$2::jsonb WHERE id=$1",[second.id,JSON.stringify([{actor:"reviewer",reason:"Compared with approved brief"}])]);expect((await pool.query("SELECT approval_state,approval_history FROM forge_artifacts WHERE id=$1",[second.id])).rows[0]).toMatchObject({approval_state:"approved",approval_history:[{actor:"reviewer",reason:"Compared with approved brief"}]})})

  it("atomically reserves budget under concurrent writes and reconciles usage",async()=>{const project=await createProject();const tasks=await Promise.all(["A","B"].map(async title=>(await pool.query("INSERT INTO forge_tasks(project_id,title,agent_type) VALUES($1,$2,'copy') RETURNING id",[project,title])).rows[0].id));const {reserveForgeAiBudget,reconcileForgeAiBudget}=await import("../../src/lib/server/forge-budget-reservations");const env={FORGE_AI_DAILY_USD_BUDGET:"1",FORGE_MAX_PROJECT_AI_COST:"1"};const settled=await Promise.allSettled(tasks.map((task,index)=>reserveForgeAiBudget({projectId:project,taskId:task,provider:"openai",model:"test",estimatedMaxCost:.6,idempotencyKey:`concurrent-${index}`,env})));expect(settled.filter(x=>x.status==="fulfilled")).toHaveLength(1);const reservation=(settled.find(x=>x.status==="fulfilled") as PromiseFulfilledResult<Awaited<ReturnType<typeof reserveForgeAiBudget>>>).value;await reconcileForgeAiBudget({reservationId:reservation.id,actualCost:.2,usageKnown:true});const row=(await pool.query("SELECT status,reserved_cost,actual_cost FROM forge_ai_budget_reservations WHERE id=$1",[reservation.id])).rows[0];expect(row).toMatchObject({status:"reconciled",reserved_cost:"0.600000",actual_cost:"0.200000"})})

  it("rolls back all writes when a transaction fails",async()=>{const client=await pool.connect();try{await client.query("BEGIN");await client.query("INSERT INTO forge_projects(name,business_name) VALUES('Rollback','Rollback Ltd')");await client.query("INSERT INTO forge_tasks(project_id,title,agent_type) VALUES(999999,'Invalid','copy')");await client.query("COMMIT")}catch{await client.query("ROLLBACK")}finally{client.release()}expect((await pool.query("SELECT count(*)::int count FROM forge_projects WHERE name='Rollback'")).rows[0].count).toBe(0)})
})
async function createProject(){return (await pool.query("INSERT INTO forge_projects(name,business_name,status) VALUES('Integration Site','Integration Ltd','intake') RETURNING id")).rows[0].id as number}
