import type { Metadata } from "next"
import Link from "next/link"
import { ArrowRight, Check, Compass, Target } from "lucide-react"
import { AnimateIn } from "@/components/AnimateIn"
import { FAQ } from "@/components/FAQ"
import { buildBusinessGrowthAuditSchema, businessGrowthAudit, formatAuditPrice } from "@/lib/business-growth-audit"

export const metadata: Metadata = { title: "Business Growth Audit | £395", description: "A £395 one-time review of your business's digital presence, customer journey, website, systems and growth opportunities, with a prioritised ScaleSmiths roadmap.", alternates: { canonical: businessGrowthAudit.slug }, openGraph: { title: "ScaleSmiths Business Growth Audit — £395", description: "Find what is holding the business back and what to fix first.", url: businessGrowthAudit.slug } }

export default function BusinessGrowthAuditPage() {
  const schema = buildBusinessGrowthAuditSchema(process.env.NEXT_PUBLIC_SITE_URL ?? "https://scalesmiths.co.uk")
  return <main>{schema.map((item, index) => <script key={index} type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(item) }} />)}
    <section className="px-6 py-20 md:px-12 md:py-28"><div className="mx-auto grid max-w-[1240px] gap-12 lg:grid-cols-[1.2fr_.8fr] lg:items-end"><AnimateIn><span className="text-xs font-semibold uppercase tracking-[.16em] text-acc">ScaleSmiths Business Growth Audit</span><h1 className="mt-4 font-syne text-[clamp(48px,8vw,94px)] font-extrabold leading-[.9] tracking-[-.05em]">Know what to fix next.</h1><p className="mt-7 max-w-[720px] text-lg leading-relaxed text-t2">A deep review of the systems, customer journey and digital presence around your business—followed by a prioritised roadmap showing what we would improve first and why.</p><div className="mt-8 flex flex-wrap items-center gap-4"><Link href={businessGrowthAudit.startPath} className="btn-primary">Start my Audit <ArrowRight size={16} /></Link><span className="text-sm text-t3">No payment is taken through this website.</span></div></AnimateIn><AnimateIn delay={.08} className="rounded-3xl border border-acc/20 bg-s1 p-8"><p className="text-xs font-semibold uppercase tracking-[.14em] text-acc">One-time professional audit</p><p className="mt-4 font-syne text-7xl font-extrabold">{formatAuditPrice()}</p><div className="mt-7 border-t border-b1 pt-6"><h2 className="font-syne text-xl font-bold">If we build it, the Audit costs nothing extra.</h2><p className="mt-3 text-sm leading-relaxed text-t2">Commission an eligible subsequent ScaleSmiths build and the full {formatAuditPrice(businessGrowthAudit.buildCreditMinor)} Audit fee is credited against it. Eligibility is confirmed in the project proposal.</p></div></AnimateIn></div></section>

    <section className="border-y border-b1 bg-s1 px-6 py-24 md:px-12"><div className="mx-auto max-w-[1240px]"><AnimateIn className="max-w-[820px]"><span className="text-xs font-semibold uppercase tracking-[.14em] text-acc">Diagnosis before prescription</span><h2 className="mt-3 font-syne text-[clamp(38px,6vw,68px)] font-extrabold leading-[.96]">You do not necessarily need another website.</h2><p className="mt-6 text-xl leading-relaxed text-t2">You need to know where the actual problem is.</p></AnimateIn><div className="mt-12 grid gap-px overflow-hidden rounded-2xl bg-b1 md:grid-cols-2">{["The site looks acceptable but does not generate enough enquiries.","Leads arrive but follow-up is inconsistent.","The business relies too heavily on referrals.","Messaging does not explain the offer clearly.","Digital systems and providers feel fragmented.","Manual administration consumes time that should create value.","Visibility is weak or disconnected from buyer intent.","You know something must improve but not where to begin."].map((item) => <div key={item} className="flex gap-3 bg-bg p-6 text-sm leading-relaxed text-t2"><Check size={16} className="mt-1 shrink-0 text-acc" />{item}</div>)}</div></div></section>

    <section className="px-6 py-24 md:px-12"><div className="mx-auto max-w-[1240px]"><AnimateIn className="max-w-[700px]"><span className="text-xs font-semibold uppercase tracking-[.14em] text-acc">What we investigate</span><h2 className="mt-3 font-syne text-5xl font-extrabold">Eight connected business lenses.</h2><p className="mt-5 leading-relaxed text-t2">Not a fifty-point checklist. A focused assessment of the areas most likely to affect trust, conversion, efficiency and growth.</p></AnimateIn><div className="mt-12 grid gap-4 md:grid-cols-2">{businessGrowthAudit.pillars.map((pillar, index) => <AnimateIn key={pillar.number} delay={index * .025} className="grid grid-cols-[auto_1fr] gap-5 border-t border-b2 py-6"><span className="text-xs font-semibold text-acc">{pillar.number}</span><div><h3 className="font-syne text-xl font-bold">{pillar.title}</h3><p className="mt-2 text-sm leading-relaxed text-t2">{pillar.copy}</p></div></AnimateIn>)}</div></div></section>

    <section className="bg-s1 px-6 py-24 md:px-12"><div className="mx-auto grid max-w-[1240px] gap-12 lg:grid-cols-[.8fr_1.2fr]"><AnimateIn><span className="text-xs font-semibold uppercase tracking-[.14em] text-acc">Your deliverable</span><h2 className="mt-3 font-syne text-5xl font-extrabold">Clarity you can act on.</h2><p className="mt-5 leading-relaxed text-t2">The Audit retains standalone value whether you implement internally, use another provider, ask ScaleSmiths to deliver, or decide an area does not currently justify investment.</p></AnimateIn><div className="grid gap-3 sm:grid-cols-2">{businessGrowthAudit.deliverables.map((item, index) => <div key={item} className="rounded-2xl border border-b1 bg-bg p-5"><span className="text-[10px] font-semibold text-acc">0{index + 1}</span><h3 className="mt-3 font-syne text-lg font-bold">{item}</h3></div>)}</div></div></section>

    <section className="px-6 py-24 md:px-12"><div className="mx-auto grid max-w-[1240px] gap-8 lg:grid-cols-2"><AnimateIn className="rounded-3xl border border-b1 bg-s1 p-7 md:p-9"><p className="text-xs font-semibold uppercase tracking-[.14em] text-acc">Example finding—not a client result</p><h2 className="mt-4 font-syne text-3xl font-bold">Enquiries depend on the phone.</h2>{[["Observation","The primary conversion path assumes visitors are ready to call during business hours."],["Impact","Prospects browsing outside those hours have no structured route to explain what they need."],["Recommendation","Add a concise qualification flow and connect submissions to a defined follow-up process."],["Priority","High"]].map(([label,copy]) => <div key={label} className="mt-6 border-t border-b1 pt-4"><p className="text-[10px] font-semibold uppercase tracking-[.12em] text-acc">{label}</p><p className="mt-2 text-sm leading-relaxed text-t2">{copy}</p></div>)}</AnimateIn><AnimateIn delay={.08} className="rounded-3xl border border-b1 bg-bg p-7 md:p-9"><p className="text-xs font-semibold uppercase tracking-[.14em] text-acc">Priority, not volume</p><h2 className="mt-4 font-syne text-3xl font-bold">Impact against effort.</h2><div className="mt-8 grid grid-cols-2 gap-3">{[["Quick wins","High impact · lower effort"],["Strategic moves","High impact · greater effort"],["Maintenance","Useful · proportionate"],["Lower priority","Not worth doing first"]].map(([title,copy], index) => <div key={title} className={`min-h-32 rounded-xl border p-4 ${index < 2 ? "border-acc/30 bg-acc/[.05]" : "border-b1 bg-s1"}`}><Target size={16} className="text-acc" /><h3 className="mt-5 font-syne text-base font-bold">{title}</h3><p className="mt-1 text-xs text-t3">{copy}</p></div>)}</div><p className="mt-6 text-sm leading-relaxed text-t2">We do not recommend doing everything. We recommend the right work in the right order.</p></AnimateIn></div></section>

    <section className="border-y border-b1 bg-s1 px-6 py-24 md:px-12"><div className="mx-auto max-w-[1240px]"><AnimateIn><span className="text-xs font-semibold uppercase tracking-[.14em] text-acc">How it works</span><h2 className="mt-3 font-syne text-5xl font-extrabold">From context to roadmap.</h2></AnimateIn><ol className="mt-12 grid gap-4 md:grid-cols-5">{[["01","Tell us about the business"],["02","We investigate"],["03","We find the gaps"],["04","You get the roadmap"],["05","You decide what happens next"]].map(([n,title]) => <li key={n} className="border-t border-acc/40 pt-5"><span className="text-xs text-acc">{n}</span><h3 className="mt-3 font-syne text-lg font-bold">{title}</h3></li>)}</ol><p className="mt-10 max-w-[720px] text-sm leading-relaxed text-t2">Once ScaleSmiths has the information needed, the Audit delivery date is confirmed before work begins. You can act on the recommendations independently; an eligible ScaleSmiths build receives the full £395 credit.</p></div></section>
    <FAQ items={[...businessGrowthAudit.faq]} />
    <section className="px-6 pb-28 md:px-12"><div className="mx-auto max-w-[1240px] rounded-3xl border border-acc/20 bg-s1 p-8 md:p-12"><Compass size={24} className="text-acc" /><h2 className="mt-5 font-syne text-[clamp(34px,5vw,58px)] font-extrabold">Find the gaps before fixing the wrong things.</h2><p className="mt-4 max-w-[680px] text-t2">A one-time {formatAuditPrice()} professional assessment with a prioritised roadmap and no obligation to commission implementation.</p><Link href={businessGrowthAudit.startPath} className="btn-primary mt-7">Start my Audit <ArrowRight size={16} /></Link></div></section>
  </main>
}
