import { mkdir, readFile, writeFile } from "node:fs/promises"
import path from "node:path"
import { PDFDocument } from "pdf-lib"
import { describe, expect, it } from "vitest"
import type { InvoiceDocumentData } from "@/lib/invoice-document"
import { invoicePdfFilename, invoicePdfTextFragments, renderInvoicePdf } from "./invoice-pdf"

describe("invoice PDF",()=>{
  it("renders an issued GBP invoice and excludes internal-only content",async()=>{const data=fixture();const bytes=await renderInvoicePdf(data);expect(Buffer.from(bytes).subarray(0,4).toString()).toBe("%PDF");expect(invoicePdfTextFragments(data)).toContain("£350.00");expect(invoicePdfTextFragments(data)).toContain("Customer-facing reference");expect(invoicePdfTextFragments(data)).not.toContain("INTERNAL SECRET");expect(invoicePdfFilename(data)).toBe("SS-CAK-0001.pdf")})
  it("renders a draft indication without fabricating a number",async()=>{const data=fixture({documentState:"draft",invoiceNumber:null,issuedDate:null});expect(invoicePdfTextFragments(data)).toContain("DRAFT");expect(invoicePdfFilename(data)).toBe("ScaleSmiths-Invoice-Draft.pdf");expect((await renderInvoicePdf(data)).length).toBeGreaterThan(1000)})
  it.each(["paid","void"] as const)("retains invoice information and indicates %s",async(documentState)=>{const data=fixture({documentState});expect(invoicePdfTextFragments(data)).toContain("SS-CAK-0001");expect((await renderInvoicePdf(data)).length).toBeGreaterThan(1000)})
  it("wraps long descriptions and paginates without failing",async()=>{const data=fixture({items:Array.from({length:55},(_,index)=>({title:`Extended service ${index+1}`,description:"A long customer-facing explanation with detailed delivery information ".repeat(8),quantity:1,unitAmount:35000,lineAmount:35000})),subtotal:1925000,total:1925000});const bytes=await renderInvoicePdf(data);expect((await PDFDocument.load(bytes)).getPageCount()).toBeGreaterThan(1)})
  it("keeps the PDF route read-authorized with correct response headers",async()=>{const route=await readFile(new URL("../../app/api/invoices/[id]/pdf/route.ts",import.meta.url),"utf8");expect(route).toContain('guardApiCapability("finance.read")');expect(route).toContain('"Content-Type": "application/pdf"');expect(route).toContain('"Content-Disposition"');expect(route).toContain('"Cache-Control": "private, no-store"')})
})

const supplier={legalName:"ScaleSmiths",tradingName:null,addressLine1:"1 High Street",addressLine2:null,city:"Leeds",county:"West Yorkshire",postcode:"LS1 1AA",country:"United Kingdom",contactEmail:"hello@scalesmiths.co.uk",website:"scalesmiths.co.uk",companyNumber:null,vatNumber:null}
const customer={businessName:"Confirm-a-Kill",contactName:"Alex Smith",email:"alex@example.com",addressLine1:"2 Market Road",addressLine2:null,city:"York",county:"North Yorkshire",postcode:"YO1 1AA",country:"United Kingdom"}
function fixture(overrides:Partial<InvoiceDocumentData>={}):InvoiceDocumentData{return{templateVersion:"scalesmiths-v1",documentState:"issued",invoiceNumber:"SS-CAK-0001",invoiceDate:"2026-08-16",dueDate:"2026-08-30",issuedDate:"2026-08-16",paidDate:null,supplier,customer,payment:{instructions:"Pay by bank transfer.",accountName:null,sortCode:null,accountNumber:null,referenceInstructions:"Use the invoice number."},customerNote:"Customer-facing reference",items:[{title:"Monthly Growth Retainer",description:"August services",quantity:1,unitAmount:35000,lineAmount:35000}],subtotal:35000,total:35000,currency:"GBP",...overrides}}

if(process.env.GENERATE_INVOICE_PDF_FIXTURES==="1") describe("PDF fixture generation",()=>{it("writes representative PDFs",async()=>{const dir=path.join(process.cwd(),"artifacts","invoice-pdf-fixtures");await mkdir(dir,{recursive:true});const fixtures:Record<string,InvoiceDocumentData>={"normal-issued":fixture(),"multi-item":fixture({items:Array.from({length:8},(_,i)=>({title:`Service ${i+1}`,description:"Professional services",quantity:1,unitAmount:35000,lineAmount:35000})),subtotal:280000,total:280000}),"long-multipage":fixture({items:Array.from({length:55},(_,i)=>({title:`Extended service ${i+1}`,description:"Detailed delivery information for this customer engagement. ".repeat(8),quantity:1,unitAmount:35000,lineAmount:35000})),subtotal:1925000,total:1925000}),void:fixture({documentState:"void"}),draft:fixture({documentState:"draft",invoiceNumber:null,issuedDate:null})};for(const[name,data]of Object.entries(fixtures))await writeFile(path.join(dir,`${name}.pdf`),await renderInvoicePdf(data));expect(Object.keys(fixtures)).toHaveLength(5)})})
