"use client"

import { useState } from "react"
import Link from "next/link"
import { EmptyState, InlineAlert, PageSection, StatusBadge, WorkspaceHeader, WorkspaceShell } from "@/components/admin-shell/primitives"
import { formatGbp, penceToInput, poundsToPence } from "@/lib/invoice-ui"
import type { CatalogueItem } from "./finance-types"

const EMPTY = { name: "", description: "", price: "0.00", category: "", position: "0", active: true }
export function CatalogueManager({ initialItems, canWrite }: { initialItems: CatalogueItem[]; canWrite: boolean }) {
  const [items, setItems] = useState(initialItems)
  const [editing, setEditing] = useState<number | "new" | null>(null)
  const [form, setForm] = useState(EMPTY)
  const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [message, setMessage] = useState("")
  function begin(item?: CatalogueItem) { setEditing(item?.id ?? "new"); setForm(item ? { name: item.name, description: item.description ?? "", price: penceToInput(item.defaultUnitAmount), category: item.category ?? "", position: String(item.position), active: item.active } : EMPTY) }
  async function save() { const amount = poundsToPence(form.price); if (amount === null) return setError("Enter a valid GBP price with no more than two decimal places."); setBusy(true); setError(""); try { const isNew = editing === "new"; const response = await fetch(isNew ? "/api/invoice-catalogue" : `/api/invoice-catalogue/${editing}`, { method: isNew ? "POST" : "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: form.name, description: form.description, defaultUnitAmount: amount, category: form.category, position: Number(form.position), active: form.active }) }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || "Unable to save catalogue item."); setItems((current) => isNew ? [...current, data.item] : current.map((item) => item.id === data.item.id ? data.item : item)); setEditing(null); setMessage(isNew ? "Service created." : "Service updated.") } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to save catalogue item.") } finally { setBusy(false) } }
  return <WorkspaceShell><WorkspaceHeader eyebrow="Finance" title="Invoice catalogue" description="Reusable service templates. Existing invoice items remain independent snapshots." actions={<div className="flex gap-2"><Link href="/finance/invoices" className="rounded-lg border border-b2 px-3 py-2 text-sm">Invoices</Link>{canWrite ? <button type="button" onClick={() => begin()} className="rounded-lg bg-acc px-4 py-2 text-sm font-semibold text-white">Create service</button> : null}</div>} />
    {error ? <InlineAlert tone="danger">{error}</InlineAlert> : null}{message ? <InlineAlert tone="success">{message}</InlineAlert> : null}
    {editing ? <PageSection title={editing === "new" ? "New service" : "Edit service"} raised><div className="grid gap-3 md:grid-cols-2"><Field label="Name"><input value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /></Field><Field label="Default price (£)"><input inputMode="decimal" value={form.price} onChange={(event) => setForm({ ...form, price: event.target.value })} /></Field><Field label="Category"><input value={form.category} onChange={(event) => setForm({ ...form, category: event.target.value })} /></Field><Field label="Order"><input type="number" value={form.position} onChange={(event) => setForm({ ...form, position: event.target.value })} /></Field><Field label="Description"><textarea rows={3} value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} /></Field><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.active} onChange={(event) => setForm({ ...form, active: event.target.checked })} /> Active for new invoices</label></div><div className="mt-4 flex gap-2"><button type="button" disabled={busy} onClick={() => void save()} className="rounded-lg bg-acc px-4 py-2 text-sm text-white">{busy ? "Saving…" : "Save service"}</button><button type="button" onClick={() => setEditing(null)} className="rounded-lg border border-b2 px-4 py-2 text-sm">Cancel</button></div></PageSection> : null}
    <PageSection raised>{items.length === 0 ? <EmptyState title="No catalogue items" description="Create your first reusable service template." action={canWrite ? <button type="button" onClick={() => begin()} className="rounded-lg bg-acc px-4 py-2 text-sm text-white">Create your first service</button> : undefined} /> : <div className="grid gap-3">{items.toSorted((a, b) => a.position - b.position || a.name.localeCompare(b.name)).map((item) => <div key={item.id} className="grid gap-3 rounded-lg border border-b1 bg-s2 p-4 md:grid-cols-[1fr_auto_auto] md:items-center"><div><div className="flex items-center gap-2"><strong>{item.name}</strong><StatusBadge tone={item.active ? "success" : "neutral"}>{item.active ? "ACTIVE" : "INACTIVE"}</StatusBadge></div><p className="mt-1 text-sm text-t2">{item.description || "No description"}{item.category ? ` · ${item.category}` : ""}</p></div><strong>{formatGbp(item.defaultUnitAmount)}</strong>{canWrite ? <button type="button" onClick={() => begin(item)} className="text-sm text-acc">Edit</button> : null}</div>)}</div>}</PageSection>
  </WorkspaceShell>
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="grid gap-1 text-sm"><span className="text-xs text-t2">{label}</span>{children}</label> }
