"use client"

import { useState } from "react"
import Link from "next/link"
import { useRouter } from "next/navigation"
import { Plus, Trash2 } from "lucide-react"
import { InlineAlert, PageSection, StatusBadge, WorkspaceHeader, WorkspaceShell } from "@/components/admin-shell/primitives"
import { addDays, canIssueVisibleDraft, catalogueLine, customLine, draftLineTotal, formatGbp, invoiceDisplayStatus, penceToInput, poundsToPence } from "@/lib/invoice-ui"
import { ConfirmationDialog } from "./ConfirmationDialog"
import { InvoiceDeliveryPanel } from "./InvoiceDeliveryPanel"
import type { CatalogueItem, FinanceClient, FinanceInvoice, InvoiceLine, InvoiceSupplierSettings } from "./finance-types"

type EditorLine = { key: string; catalogueItemId: number | null; title: string; description: string; quantity: string; unitPrice: string }
type ConfirmAction = "issue" | "delete" | "paid" | "void" | "code" | null

export function InvoiceBuilder({ initialInvoice, clients, catalogue, supplierSettings, canWrite }: { initialInvoice?: FinanceInvoice; clients: FinanceClient[]; catalogue: CatalogueItem[]; supplierSettings: InvoiceSupplierSettings | null; canWrite: boolean }) {
  const router = useRouter()
  const initialClient = initialInvoice?.client ?? clients.find((client) => client.id === initialInvoice?.clientId) ?? null
  const [invoice, setInvoice] = useState(initialInvoice)
  const [client, setClient] = useState<FinanceClient | null>(initialClient)
  const [invoiceDate, setInvoiceDate] = useState(dateInput(initialInvoice?.invoiceDate) || dateInput(new Date()))
  const [dueDate, setDueDate] = useState(dateInput(initialInvoice?.dueDate) || addDays(dateInput(new Date()), 14))
  const [dueOverridden, setDueOverridden] = useState(Boolean(initialInvoice))
  const [customerNotes, setCustomerNotes] = useState(initialInvoice?.customerNotes ?? "")
  const [internalNotes, setInternalNotes] = useState(initialInvoice?.internalNotes ?? "")
  const [lines, setLines] = useState<EditorLine[]>(() => initialInvoice?.items?.map(editorLine) ?? [])
  const [dirty, setDirty] = useState(false)
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState("")
  const [message, setMessage] = useState("")
  const [confirm, setConfirm] = useState<ConfirmAction>(null)
  const [catalogueId, setCatalogueId] = useState("")
  const [code, setCode] = useState("")
  const editable = !invoice || invoice.status === "draft"
  const mutable = editable && canWrite
  const activeCatalogue = catalogue.filter((item) => item.active)
  const parsedLines = lines.map((line) => ({ ...line, quantityNumber: Number(line.quantity), unitPence: poundsToPence(line.unitPrice) }))
  const optimisticTotal = parsedLines.reduce((total, line) => Number.isSafeInteger(line.quantityNumber) && line.quantityNumber > 0 && line.unitPence !== null ? total + line.quantityNumber * line.unitPence : total, 0)
  const blockers = (() => {
    const values: string[] = []
    if (!client) values.push("Select a client.")
    if (!client?.invoiceClientCode) values.push("Assign a permanent invoice client code.")
    if (!client || !client.billingAddressLine1 || !client.billingCity || !client.billingPostcode || !client.billingCountry) values.push("Complete the client's billing address.")
    if (!supplierSettings || !(supplierSettings.legalName || supplierSettings.tradingName)) values.push("Complete the ScaleSmiths supplier business name in invoice settings.")
    if (!supplierSettings?.addressLine1 || !supplierSettings.city || !supplierSettings.postcode || !supplierSettings.country) values.push("Complete the ScaleSmiths supplier address in invoice settings.")
    if (!lines.length) values.push("Add at least one invoice item.")
    if (parsedLines.some((line) => !line.title.trim() || !Number.isSafeInteger(line.quantityNumber) || line.quantityNumber <= 0 || line.unitPence === null)) values.push("Correct invalid item titles, quantities or prices.")
    if (!invoiceDate || !dueDate || dueDate < invoiceDate) values.push("Choose valid invoice and due dates.")
    return values
  })()
  const missingBilling = client ? !client.billingAddressLine1 || !client.billingCity || !client.billingPostcode || !client.billingCountry : false

  function changeDate(value: string) { setInvoiceDate(value); if (!dueOverridden) setDueDate(addDays(value, 14)); markDirty() }
  function markDirty() { if (invoice) setDirty(true) }
  function selectClient(id: string) { setClient(clients.find((item) => item.id === Number(id)) ?? null); markDirty() }
  function addCatalogue() { const item = activeCatalogue.find((entry) => entry.id === Number(catalogueId)); if (!item) return; setLines((current) => [...current, { key: crypto.randomUUID(), ...catalogueLine(item) }]); setCatalogueId(""); markDirty() }
  function addCustom() { setLines((current) => [...current, { key: crypto.randomUUID(), ...customLine() }]); markDirty() }
  function updateLine(key: string, field: keyof EditorLine, value: string) { setLines((current) => current.map((line) => line.key === key ? { ...line, [field]: value } : line)); markDirty() }
  function removeLine(key: string) { setLines((current) => current.filter((line) => line.key !== key)); markDirty() }

  async function save() {
    if (!client || parsedLines.some((line) => line.unitPence === null)) return setError("Correct the invoice before saving.")
    setBusy(true); setError(""); setMessage("")
    try {
      const response = await fetch(invoice ? `/api/invoices/${invoice.id}` : "/api/invoices", { method: invoice ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ clientId: client.id, invoiceDate, dueDate, customerNotes, internalNotes, items: parsedLines.map((line) => ({ catalogueItemId: line.catalogueItemId, title: line.title, description: line.description, quantity: line.quantityNumber, unitAmount: line.unitPence })) }) })
      const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || "Unable to save invoice.")
      const saved = data.invoice as FinanceInvoice; setInvoice(saved); setLines((saved.items ?? []).map(editorLine)); setDirty(false); setMessage("Draft saved.")
      if (!invoice) router.replace(`/finance/invoices/${saved.id}`)
    } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to save invoice.") } finally { setBusy(false) }
  }

  async function transition(action: "issue" | "mark_paid" | "void") {
    if (!invoice) return
    setBusy(true); setError("")
    try { const response = await fetch(`/api/invoices/${invoice.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action }) }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || "Unable to update invoice."); setInvoice(data.invoice); setLines((data.invoice.items ?? []).map(editorLine)); setDirty(false); setMessage(action === "issue" ? `Invoice issued as ${data.invoice.invoiceNumber}.` : action === "mark_paid" ? "Invoice marked paid." : "Invoice voided; its number remains permanently recorded."); setConfirm(null); router.refresh() } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to update invoice.") } finally { setBusy(false) }
  }
  async function deleteDraft() { if (!invoice) return; setBusy(true); try { const response = await fetch(`/api/invoices/${invoice.id}`, { method: "DELETE" }); if (!response.ok) throw new Error((await response.json().catch(() => ({}))).error || "Unable to delete draft."); router.push("/finance/invoices"); router.refresh() } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to delete draft."); setConfirm(null); setBusy(false) } }
  async function assignCode() { if (!client) return; setBusy(true); setError(""); try { const response = await fetch(`/api/clients/${client.id}/invoice-code`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ invoiceClientCode: code }) }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || "Unable to assign code."); setClient(data.client); setCode(""); setConfirm(null); setMessage("Permanent invoice code assigned.") } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to assign code.") } finally { setBusy(false) } }

  const displayedTotal = invoice && !dirty ? invoice.total : optimisticTotal
  const displayStatus = invoice ? invoiceDisplayStatus(invoice) : "draft"
  return <WorkspaceShell>
    <WorkspaceHeader eyebrow="Finance · Invoices" title={invoice?.invoiceNumber ?? "Draft invoice"} description={invoice ? `${invoice.clientNameSnapshot} · ${formatGbp(invoice.total)}` : "Build a draft using current client and catalogue information."} leading={<Link href="/finance/invoices" className="text-sm text-acc">← Invoices</Link>} meta={<StatusBadge tone={displayStatus === "paid" ? "success" : displayStatus === "overdue" || displayStatus === "void" ? "danger" : displayStatus === "issued" ? "info" : "warning"}>{displayStatus.toUpperCase()}</StatusBadge>} />
    {error ? <InlineAlert tone="danger">{error}</InlineAlert> : null}{message ? <InlineAlert tone="success">{message}</InlineAlert> : null}
    {!canWrite && editable ? <InlineAlert tone="info">You have read-only finance access. Mutation controls are unavailable.</InlineAlert> : null}
    <div className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_330px]">
      <div className="space-y-4">
        <PageSection title="Client and billing" description={invoice && !editable ? "Locked issue-time billing snapshot" : "Current client details will be finalized when issued."} raised>
          {editable ? <select disabled={!mutable || Boolean(invoice)} value={client?.id ?? ""} onChange={(event) => selectClient(event.target.value)} aria-label="Invoice client" className="w-full rounded-lg border border-b2 bg-s2 px-3 py-2"><option value="">Select a client</option>{clients.map((item) => <option key={item.id} value={item.id}>{item.name} · {item.contactName ?? "No contact"} · {item.invoiceClientCode ?? "code required"}</option>)}</select> : <strong>{invoice?.clientNameSnapshot}</strong>}
          {client ? <BillingSummary client={client} invoice={invoice} editable={editable} /> : null}
          {client && editable && canWrite ? <ClientBillingEditor client={client} onSaved={(saved) => { setClient(saved); setMessage("Client billing details updated.") }} /> : null}
          {client && !client.invoiceClientCode && editable ? <div className="mt-4 rounded-lg border border-amber-500/30 bg-amber-500/10 p-4"><strong>Invoice code required before issue</strong><p className="mt-1 text-sm text-t2">Choose the permanent client code deliberately. It cannot be silently changed.</p>{canWrite ? <div className="mt-3 flex gap-2"><input value={code} onChange={(event) => setCode(event.target.value.toUpperCase())} placeholder="CAK" maxLength={12} className="w-32 rounded-lg border border-b2 bg-s2 px-3 py-2 uppercase" /><button type="button" disabled={!/^[A-Z0-9]{2,12}$/.test(code)} onClick={() => setConfirm("code")} className="rounded-lg bg-acc px-3 py-2 text-sm text-white disabled:opacity-50">Assign code</button></div> : null}{code ? <p className="mt-2 font-mono text-xs">Future invoices will use SS-{code}-0001, SS-{code}-0002, …</p> : null}</div> : null}
          {missingBilling && editable ? <InlineAlert tone="warning">Billing address is incomplete and must be completed before issuing.</InlineAlert> : null}
        </PageSection>
        <PageSection title="Dates" raised><div className="grid gap-4 sm:grid-cols-2"><Field label="Invoice Date"><input type="date" disabled={!mutable} value={invoiceDate} onChange={(event) => changeDate(event.target.value)} /></Field><Field label="Due Date"><input type="date" disabled={!mutable} value={dueDate} onChange={(event) => { setDueDate(event.target.value); setDueOverridden(true); markDirty() }} /></Field></div></PageSection>
        <PageSection title="Line items" description={editable ? "Catalogue values are copied and remain editable on this invoice." : "Financial line items are locked."} actions={mutable ? <div className="flex flex-wrap gap-2"><select value={catalogueId} onChange={(event) => setCatalogueId(event.target.value)} aria-label="Catalogue service" className="rounded-lg border border-b2 bg-s2 px-2 py-2 text-sm"><option value="">Choose service</option>{activeCatalogue.map((item) => <option key={item.id} value={item.id}>{item.name} · {formatGbp(item.defaultUnitAmount)}</option>)}</select><button type="button" onClick={addCatalogue} disabled={!catalogueId} className="rounded-lg bg-acc px-3 py-2 text-sm text-white disabled:opacity-50">Add Item</button><button type="button" onClick={addCustom} className="inline-flex items-center gap-1 rounded-lg border border-b2 px-3 py-2 text-sm"><Plus size={14} /> Add Custom Item</button></div> : undefined} raised>
          {lines.length ? <div className="space-y-3">{lines.map((line, index) => <div key={line.key} className="grid gap-3 rounded-lg border border-b1 bg-s2 p-3 lg:grid-cols-[minmax(180px,2fr)_100px_130px_110px_auto]"><div className="space-y-2"><input aria-label={`Item ${index + 1} title`} disabled={!mutable} value={line.title} onChange={(event) => updateLine(line.key, "title", event.target.value)} placeholder="Service or product" className="w-full font-medium" /><textarea aria-label={`Item ${index + 1} description`} disabled={!mutable} value={line.description} onChange={(event) => updateLine(line.key, "description", event.target.value)} placeholder="Description" rows={2} className="w-full text-sm" /></div><Field label="Quantity"><input aria-label={`Item ${index + 1} quantity`} disabled={!mutable} inputMode="numeric" value={line.quantity} onChange={(event) => updateLine(line.key, "quantity", event.target.value)} /></Field><Field label="Unit price (£)"><input aria-label={`Item ${index + 1} unit price`} disabled={!mutable} inputMode="decimal" value={line.unitPrice} onChange={(event) => updateLine(line.key, "unitPrice", event.target.value)} /></Field><div><span className="block text-xs text-t2">Line total</span><strong className="mt-2 block">{formatGbp(validLineTotal(line))}</strong></div>{mutable ? <button type="button" onClick={() => removeLine(line.key)} aria-label={`Remove item ${index + 1}`} className="self-start rounded-lg p-2 text-red-300"><Trash2 size={16} /></button> : null}</div>)}</div> : <p className="py-8 text-center text-sm text-t2">No invoice items yet.</p>}
        </PageSection>
        <PageSection title="Notes" raised><div className="grid gap-4 lg:grid-cols-2"><Field label="Customer-visible note / reference"><textarea disabled={!mutable} value={customerNotes} onChange={(event) => { setCustomerNotes(event.target.value); markDirty() }} rows={4} /></Field><Field label="Internal note"><textarea disabled={!mutable} value={internalNotes} onChange={(event) => { setInternalNotes(event.target.value); markDirty() }} rows={4} /><span className="text-xs text-t2">Never shown in customer-facing invoice output.</span></Field></div></PageSection>
      </div>
      <aside className="space-y-4">{invoice && invoice.status !== "draft" ? <InvoiceDeliveryPanel invoice={invoice} canWrite={canWrite} onPublished={(published) => setInvoice({ ...invoice, ...published })} /> : null}<PageSection title="Totals" raised><div className="space-y-3"><TotalRow label="Subtotal" value={displayedTotal} /><div className="border-t border-b1 pt-3"><TotalRow label="Total" value={displayedTotal} strong /></div></div></PageSection>
        {invoice ? <PageSection title="Invoice document" raised><div className="grid gap-2"><a href={`/api/invoices/${invoice.id}/pdf`} target="_blank" rel="noreferrer" className="rounded-lg border border-b2 px-4 py-2 text-center text-sm font-medium">{invoice.status === "draft" ? "Preview PDF" : "View / Preview Invoice"}</a>{invoice.status !== "draft" ? <a href={`/api/invoices/${invoice.id}/pdf?download=1`} className="rounded-lg border border-b2 px-4 py-2 text-center text-sm font-medium">Download PDF</a> : null}</div></PageSection> : null}
        {invoice && invoice.status !== "draft" ? <PageSection title="Invoice record" raised><dl className="space-y-2 text-sm"><Meta label="Issued" value={dateTime(invoice.issuedAt)} />{invoice.paidAt ? <Meta label="Paid" value={dateTime(invoice.paidAt)} /> : null}{invoice.voidedAt ? <Meta label="Voided" value={dateTime(invoice.voidedAt)} /> : null}</dl></PageSection> : null}
        {blockers.length && editable ? <InlineAlert tone="warning"><strong>Before issue</strong><ul className="mt-1 list-disc pl-4">{blockers.map((blocker) => <li key={blocker}>{blocker}</li>)}</ul></InlineAlert> : null}
        {mutable ? <div className="grid gap-2"><button type="button" disabled={busy} onClick={() => void save()} className="rounded-lg bg-acc px-4 py-3 font-semibold text-white disabled:opacity-60">{invoice ? "Save Changes" : "Save Draft"}</button>{invoice ? <><button type="button" disabled={busy || !canIssueVisibleDraft(dirty, blockers)} onClick={() => setConfirm("issue")} className="rounded-lg bg-emerald-600 px-4 py-3 font-semibold text-white disabled:opacity-40">Issue Invoice</button>{dirty ? <p className="text-xs text-amber-300">Save changes before issuing so the persisted draft matches this screen.</p> : null}<button type="button" disabled={busy} onClick={() => setConfirm("delete")} className="rounded-lg border border-red-500/40 px-4 py-2 text-red-300">Delete Draft</button></> : null}</div> : null}
        {invoice?.status === "issued" && canWrite ? <div className="grid gap-2"><button type="button" onClick={() => setConfirm("paid")} className="rounded-lg bg-emerald-600 px-4 py-3 font-semibold text-white">Mark Paid</button><button type="button" onClick={() => setConfirm("void")} className="rounded-lg border border-red-500/40 px-4 py-2 text-red-300">Void Invoice</button></div> : null}
      </aside>
    </div>
    <ConfirmationDialog open={confirm !== null} title={confirmTitle(confirm)} confirmLabel={confirmLabel(confirm)} danger={confirm === "delete" || confirm === "void"} busy={busy} onCancel={() => setConfirm(null)} onConfirm={() => { if (confirm === "issue") void transition("issue"); else if (confirm === "paid") void transition("mark_paid"); else if (confirm === "void") void transition("void"); else if (confirm === "delete") void deleteDraft(); else if (confirm === "code") void assignCode() }}><ConfirmContent action={confirm} client={client} invoiceDate={invoiceDate} dueDate={dueDate} total={displayedTotal} code={code} /></ConfirmationDialog>
  </WorkspaceShell>
}

function BillingSummary({ client, invoice, editable }: { client: FinanceClient; invoice?: FinanceInvoice; editable: boolean }) { const values = editable ? client : { contactName: invoice?.billingContactNameSnapshot, contactEmail: invoice?.billingEmailSnapshot, billingAddressLine1: invoice?.billingAddressLine1Snapshot, billingAddressLine2: invoice?.billingAddressLine2Snapshot, billingCity: invoice?.billingCitySnapshot, billingCounty: invoice?.billingCountySnapshot, billingPostcode: invoice?.billingPostcodeSnapshot, billingCountry: invoice?.billingCountrySnapshot }; return <div className="mt-4 grid gap-1 text-sm text-t2"><span>{values.contactName || "No billing contact"}{values.contactEmail ? ` · ${values.contactEmail}` : ""}</span><span>{[values.billingAddressLine1, values.billingAddressLine2, values.billingCity, values.billingCounty, values.billingPostcode, values.billingCountry].filter(Boolean).join(", ") || "No billing address"}</span></div> }
function ClientBillingEditor({ client, onSaved }: { client: FinanceClient; onSaved: (client: FinanceClient) => void }) { const [open, setOpen] = useState(false); const [values, setValues] = useState(client); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); async function save() { setBusy(true); setError(""); try { const response = await fetch(`/api/clients/${client.id}/billing`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(values) }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || "Unable to update billing details."); onSaved(data.client); setValues(data.client); setOpen(false) } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to update billing details.") } finally { setBusy(false) } } if (!open) return <button type="button" onClick={() => setOpen(true)} className="mt-3 text-sm text-acc">Update client billing details</button>; const fields: Array<[keyof FinanceClient, string]> = [["contactName", "Billing contact"], ["contactEmail", "Billing email"], ["billingAddressLine1", "Address line 1"], ["billingAddressLine2", "Address line 2"], ["billingCity", "City / town"], ["billingCounty", "County / region"], ["billingPostcode", "Postcode / postal code"], ["billingCountry", "Country"], ["portalClientId", "Portal client ID"]]; return <div className="mt-4 rounded-lg border border-b1 bg-s2 p-4"><div className="grid gap-3 sm:grid-cols-2">{fields.map(([key, label]) => <Field key={key} label={label}><input value={String(values[key] ?? "")} onChange={(event) => setValues({ ...values, [key]: event.target.value || null })} /></Field>)}</div>{error ? <p className="mt-2 text-sm text-red-300">{error}</p> : null}<div className="mt-3 flex gap-2"><button type="button" disabled={busy} onClick={() => void save()} className="rounded-lg bg-acc px-3 py-2 text-sm text-white">{busy ? "Saving…" : "Save billing details"}</button><button type="button" onClick={() => setOpen(false)} className="rounded-lg border border-b2 px-3 py-2 text-sm">Cancel</button></div></div> }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="grid gap-1 text-sm"><span className="text-xs font-medium text-t2">{label}</span>{children}</label> }
function TotalRow({ label, value, strong = false }: { label: string; value: number; strong?: boolean }) { return <div className="flex justify-between gap-4"><span className="text-t2">{label}</span><span className={strong ? "text-xl font-bold" : "font-semibold"}>{formatGbp(value)}</span></div> }
function Meta({ label, value }: { label: string; value: string }) { return <div className="flex justify-between gap-2"><dt className="text-t2">{label}</dt><dd>{value}</dd></div> }
function editorLine(line: InvoiceLine): EditorLine { return { key: String(line.id ?? crypto.randomUUID()), catalogueItemId: line.catalogueItemId, title: line.title, description: line.description ?? "", quantity: String(line.quantity), unitPrice: penceToInput(line.unitAmount) } }
function validLineTotal(line: EditorLine) { return draftLineTotal(line.quantity, line.unitPrice) }
function dateInput(value?: Date | string) { return value ? new Date(value).toISOString().slice(0, 10) : "" }
function dateTime(value: Date | string | null | undefined) { return value ? new Intl.DateTimeFormat("en-GB", { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "—" }
function confirmTitle(action: ConfirmAction) { return action === "issue" ? "Issue this invoice?" : action === "delete" ? "Delete this draft?" : action === "paid" ? "Mark invoice as paid?" : action === "void" ? "Void this invoice?" : action === "code" ? "Assign permanent client code?" : "Confirm action" }
function confirmLabel(action: ConfirmAction) { return action === "issue" ? "Issue Invoice" : action === "delete" ? "Delete Draft" : action === "paid" ? "Mark Paid" : action === "void" ? "Void Invoice" : action === "code" ? "Assign Permanently" : "Confirm" }
function ConfirmContent({ action, client, invoiceDate, dueDate, total, code }: { action: ConfirmAction; client: FinanceClient | null; invoiceDate: string; dueDate: string; total: number; code: string }) { if (action === "issue") return <><p>Issuing allocates a permanent ScaleSmiths invoice number and locks the client snapshot, dates, line items and total. It cannot then be ordinarily edited or deleted.</p><dl className="grid grid-cols-2 gap-1 rounded-lg bg-s2 p-3"><dt>Client</dt><dd>{client?.name}</dd><dt>Invoice date</dt><dd>{invoiceDate}</dd><dt>Due date</dt><dd>{dueDate}</dd><dt>Total</dt><dd>{formatGbp(total)}</dd></dl><p>A permanent invoice number will be allocated by the server when issued.</p></>; if (action === "void") return <p>The invoice remains in permanent financial history and its number will never be reused.</p>; if (action === "delete") return <p>This deletes the unissued draft. No permanent invoice number has been allocated.</p>; if (action === "code") return <p><strong>{code}</strong> will permanently identify {client?.name}. Future references will use SS-{code}-0001, SS-{code}-0002, and so on.</p>; return <p>Confirm this financial status change.</p> }
