"use client"
import { useEffect, useState } from "react"
import { InlineAlert, PageSection } from "@/components/admin-shell/primitives"
import { formatGbp, invoiceDisplayStatus } from "@/lib/invoice-ui"
import { ConfirmationDialog } from "./ConfirmationDialog"
import type { FinanceInvoice } from "./finance-types"

type Action="publish"|"send_invoice"|"send_reminder"|null
type Delivery={id:number;deliveryType:"invoice"|"reminder";recipient:string;state:"pending"|"sent"|"failed";createdAt:string;sentAt:string|null;failedAt:string|null;providerMessageId:string|null}
export function InvoiceDeliveryPanel({invoice,canWrite,onPublished}:{invoice:FinanceInvoice;canWrite:boolean;onPublished:(invoice:FinanceInvoice)=>void}){
 const [history,setHistory]=useState<Delivery[]>([]),[action,setAction]=useState<Action>(null),[recipient,setRecipient]=useState(invoice.billingEmailSnapshot??""),[busy,setBusy]=useState(false),[error,setError]=useState("")
 const [access,setAccess]=useState<Array<{accessType:"view"|"download";createdAt:string}>>([])
 useEffect(()=>{let active=true;fetch("/api/invoices/"+invoice.id+"/delivery").then(r=>r.json()).then(data=>{if(active){setHistory(data.deliveries??[]);setAccess(data.access??[])}}).catch(()=>{if(active)setError("Unable to load delivery history.")});return()=>{active=false}},[invoice.id])
 async function confirm(){if(!action)return;setBusy(true);setError("");try{const operationKey=crypto.randomUUID();const response=await fetch("/api/invoices/"+invoice.id+"/delivery",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,recipient,operationKey})});const data=await response.json().catch(()=>({}));if(action!=="publish"&&data.delivery)setHistory(current=>[data.delivery,...current.filter(item=>item.id!==data.delivery.id)]);if(!response.ok)throw new Error(data.error||"Delivery action failed.");if(action==="publish")onPublished(data.invoice);setAction(null)}catch(caught){setError(caught instanceof Error?caught.message:"Delivery action failed.")}finally{setBusy(false)}}
 const reminder=invoice.status==="issued";const overdue=invoiceDisplayStatus(invoice)==="overdue"
 return <><PageSection title="Delivery" raised>{error?<InlineAlert tone="danger">{error}</InlineAlert>:null}<div className="grid gap-2 text-sm"><span>{invoice.portalPublishedAt?"Published to portal "+display(invoice.portalPublishedAt):"Not published to portal"}</span>{canWrite&&invoice.status!=="draft"&&!invoice.portalPublishedAt?<button onClick={()=>setAction("publish")} className="rounded-lg border border-b2 px-3 py-2">Publish to Client Portal</button>:null}{canWrite&&invoice.status!=="draft"?<><input type="email" aria-label="Invoice recipient" value={recipient} onChange={event=>setRecipient(event.target.value)} placeholder="Recipient email"/><button onClick={()=>setAction("send_invoice")} className="rounded-lg border border-b2 px-3 py-2">Send Invoice</button></>:null}{canWrite&&reminder?<button onClick={()=>setAction("send_reminder")} className="rounded-lg border border-b2 px-3 py-2">{overdue?"Send Overdue Reminder":"Send Payment Reminder"}</button>:null}</div><div className="mt-4 space-y-2">{history.length?history.map(item=><div key={item.id} className="rounded-lg border border-b1 p-3 text-xs"><strong>{item.deliveryType==="reminder"?"Payment reminder":"Invoice emailed"}</strong><div>{item.recipient}</div><div>{display(item.sentAt||item.failedAt||item.createdAt)} · {item.state.toUpperCase()}</div>{item.state==="failed"&&canWrite?<button onClick={()=>setAction(item.deliveryType==="reminder"?"send_reminder":"send_invoice")} className="mt-1 text-acc">Retry</button>:null}</div>):<span className="text-t2">No email attempts yet.</span>}</div>{access.length?<div className="mt-4 text-xs text-t2">Last portal access: {access[0].accessType === "download" ? "PDF downloaded" : "Viewed in portal"} {display(access[0].createdAt)}</div>:null}</PageSection><ConfirmationDialog open={action!==null} title={action==="publish"?"Publish to client portal?":action==="send_reminder"?"Send payment reminder?":"Send invoice?"} confirmLabel={action==="publish"?"Publish":"Send"} busy={busy} onCancel={()=>setAction(null)} onConfirm={()=>void confirm()}><p>{action==="publish"?"This makes the issued invoice available to the explicitly linked portal account.":"The immutable PDF will be attached and the exact recipient recorded."}</p><dl className="mt-3 grid grid-cols-2 gap-1"><dt>Invoice</dt><dd>{invoice.invoiceNumber}</dd><dt>Client</dt><dd>{invoice.clientNameSnapshot}</dd><dt>Recipient</dt><dd>{recipient||"Not provided"}</dd><dt>Total</dt><dd>{formatGbp(invoice.total)}</dd></dl></ConfirmationDialog></>
}
function display(value:Date|string){return new Intl.DateTimeFormat("en-GB",{dateStyle:"medium",timeStyle:"short"}).format(new Date(value))}
