"use client"
import Link from "next/link"
import { ArrowRight, Mail, SearchCheck } from "lucide-react"
import { AnimateIn } from "./AnimateIn"
import { businessGrowthAudit, formatAuditPrice } from "@/lib/business-growth-audit"
import { managedBusinessEmail, managedBusinessEmailPriceLabel } from "@/lib/managed-business-email"
import { trackQuoteCta } from "@/lib/experience-analytics-client"

export function EntryProducts() { return <section aria-labelledby="entry-products-heading" className="border-y border-b1 bg-s1 px-6 py-24 md:px-12"><div className="mx-auto max-w-[1240px]"><AnimateIn className="max-w-[760px]"><span className="text-xs font-semibold uppercase tracking-[.14em] text-acc">Start with ScaleSmiths</span><h2 id="entry-products-heading" className="mt-3 font-syne text-[clamp(38px,6vw,68px)] font-extrabold leading-[.95]">Two focused ways to begin.</h2><p className="mt-5 text-lg leading-relaxed text-t2">You do not need to commission a five-figure project to start working with ScaleSmiths. Begin with diagnosis or with one professionally managed part of the digital estate.</p></AnimateIn><div className="mt-12 grid gap-4 lg:grid-cols-2">
  <AnimateIn className="group rounded-3xl border border-acc/20 bg-bg p-7 md:p-9"><div className="flex items-center justify-between"><span className="text-xs font-semibold uppercase tracking-[.14em] text-acc">Diagnose / plan</span><SearchCheck size={20} className="text-acc" /></div><h3 className="mt-8 font-syne text-3xl font-bold">Business Growth Audit</h3><p className="mt-3 font-syne text-2xl font-bold text-acc">{formatAuditPrice()} <span className="font-dm text-xs font-medium uppercase tracking-[.1em] text-t3">one-time</span></p><p className="mt-5 text-base leading-relaxed text-t2">Find the gaps before spending money fixing the wrong things. We review the customer journey, website, visibility, systems and growth opportunities around the business, then provide a prioritised roadmap.</p><ul className="mt-6 space-y-2 text-sm text-t2"><li>Business-wide assessment</li><li>Prioritised recommendations</li><li>Clear next steps</li><li>Full {formatAuditPrice(businessGrowthAudit.buildCreditMinor)} credited against an eligible ScaleSmiths build</li></ul><Link href={businessGrowthAudit.slug} onClick={() => trackQuoteCta(businessGrowthAudit.slug)} className="mt-8 inline-flex items-center gap-2 border-b border-acc pb-2 text-sm font-semibold text-t1">Explore the Audit <ArrowRight size={15} className="transition-transform group-hover:translate-x-1" /></Link></AnimateIn>
  <AnimateIn delay={.06} className="group rounded-3xl border border-b1 bg-bg p-7 md:p-9"><div className="flex items-center justify-between"><span className="text-xs font-semibold uppercase tracking-[.14em] text-acc">Infrastructure / operate</span><Mail size={20} className="text-acc" /></div><h3 className="mt-8 font-syne text-3xl font-bold">Managed Business Email</h3><p className="mt-3 font-syne text-2xl font-bold text-acc">From {managedBusinessEmailPriceLabel()}</p><p className="mt-5 text-base leading-relaxed text-t2">Professional business email without the technical headache. ScaleSmiths configures the custom domain, authentication and initial mailboxes, then remains available for support.</p><ul className="mt-6 space-y-2 text-sm text-t2"><li>{managedBusinessEmail.standalone.mailboxes} professional mailboxes</li><li>{managedBusinessEmail.standalone.storagePerMailboxGb}GB each</li><li>SPF, DKIM and DMARC configuration</li><li>Initial setup included</li></ul><Link href={managedBusinessEmail.slug} onClick={() => trackQuoteCta(managedBusinessEmail.slug)} className="mt-8 inline-flex items-center gap-2 border-b border-acc pb-2 text-sm font-semibold text-t1">Explore Business Email <ArrowRight size={15} className="transition-transform group-hover:translate-x-1" /></Link></AnimateIn>
  </div><div className="mt-10 grid gap-3 border-t border-b1 pt-7 text-sm md:grid-cols-3"><p><strong className="text-t1">Start</strong><span className="mt-1 block text-t3">Audit or Managed Email</span></p><p><strong className="text-t1">Grow</strong><span className="mt-1 block text-t3">Website, commerce or custom systems</span></p><p><strong className="text-t1">Partner</strong><span className="mt-1 block text-t3">Digital Growth Partnership</span></p></div></div></section> }
